<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">
  <file datatype="xml" original="markdown" source-language="en-US" target-language="hu-hu">
    <header>
      <tool tool-id="mdxliff" tool-name="mdxliff" tool-version="1.0-192e1fd" tool-company="Microsoft" />
      <xliffext:olfilehash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">48397b0b4319e8790777317fd7a8437422b234a8</xliffext:olfilehash>
      <xliffext:olfilepath xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">fulldocset\System.NotFiniteNumberException.yml</xliffext:olfilepath>
      <xliffext:oltranslationpriority xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">fulldocset</xliffext:oltranslationpriority>
      <xliffext:oltranslationtype xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">Human Translation</xliffext:oltranslationtype>
      <xliffext:olskeletonhash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">68c68859ce2bc32cb584c3037b2e29d32581c875</xliffext:olskeletonhash>
      <xliffext:olxliffhash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">13bdc11ec948a096507fe3346135c87e87679d46</xliffext:olxliffhash>
    </header>
    <body>
      <group id="content" extype="content">
        <trans-unit id="101" translate="yes" xml:space="preserve">
          <source>The exception that is thrown when a floating-point value is positive infinity, negative infinity, or Not-a-Number (NaN).</source>
          <target state="translated">A kivétel fordul elő, ha egy lebegőpontos érték pozitív végtelen, negatív végtelen, vagy nem szám (érték NaN).</target>       </trans-unit>
        <trans-unit id="102" translate="yes" xml:space="preserve" extradata="MT">
          <source>NotFiniteNumberException is available for programming languages that do not support the concepts of infinity and Not-a-Number in floating-point operations.</source>
          <target state="translated">Programozási nyelvek, amelyek nem támogatják az infinity és a nem szám a lebegőpontos műveletek NotFiniteNumberException érhető el.</target>       </trans-unit>
        <trans-unit id="103" translate="yes" xml:space="preserve" extradata="MT">
          <source>NotFiniteNumberException uses the HRESULT COR_E_NOTFINITENUMBER, which has the value 0x80131528.</source>
          <target state="translated">NotFiniteNumberException használja a HRESULT COR_E_NOTFINITENUMBER, amely 0x80131528 értékkel rendelkezik.</target>       </trans-unit>
        <trans-unit id="104" translate="yes" xml:space="preserve" extradata="MT">
          <source>For a list of initial property values for an instance of NotFiniteNumberException, see the &lt;xref:System.NotFiniteNumberException.%23ctor%2A&gt; constructors.</source>
          <target state="translated">A kezdeti tulajdonságértékek NotFiniteNumberException példányt listájáért lásd: a &lt;xref:System.NotFiniteNumberException.%23ctor%2A&gt;konstruktorok.&lt;/xref:System.NotFiniteNumberException.%23ctor%2A&gt;</target>       </trans-unit>
        <trans-unit id="105" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.NotFiniteNumberException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class.</source>
          <target state="translated">Egy új példányát inicializálja a <bpt id="p1">&lt;xref href="System.NotFiniteNumberException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> osztály.</target>       </trans-unit>
        <trans-unit id="106" translate="yes" xml:space="preserve" extradata="MT">
          <source>This constructor initializes the &lt;xref:System.Exception.Message%2A&gt; property of the new instance to a system-supplied message that describes the error, such as "The number encountered was not a finite quantity."</source>
          <target state="translated">Ez a konstruktor inicializálja a &lt;xref:System.Exception.Message%2A&gt;tulajdonság az új példány egy rendszer által megadott üzenetet, amely leírja a hibát, például "a beolvasott szám nem véges mennyiség."&lt;/xref:System.Exception.Message%2A&gt;</target>       </trans-unit>
        <trans-unit id="107" translate="yes" xml:space="preserve" extradata="MT">
          <source>This message takes into account the current system culture.</source>
          <target state="translated">Ez az üzenet figyelembe veszi a rendszer jelenlegi kulturális környezethez.</target>       </trans-unit>
        <trans-unit id="108" translate="yes" xml:space="preserve" extradata="MT">
          <source>The following table shows the initial property values for an instance of &lt;xref:System.NotFiniteNumberException&gt;.</source>
          <target state="translated">Az alábbi táblázat a kezdeti tulajdonságértékek &lt;xref:System.NotFiniteNumberException&gt;.&lt;/xref:System.NotFiniteNumberException&gt; példánya</target>       </trans-unit>
        <trans-unit id="109" translate="yes" xml:space="preserve" extradata="MT">
          <source>|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|A null reference (<ph id="ph1">`Nothing`</ph> in Visual Basic).|   |&lt;xref:System.Exception.Message%2A&gt;|The localized error message string.|</source>
          <target state="translated">| Tulajdonság |} Érték |}   |--------------|-----------|   | &lt;xref:System.Exception.InnerException%2A&gt;| Egy null hivatkozás (<ph id="ph1">`Nothing`</ph> a Visual Basic nyelvben). |}   | &lt;xref:System.Exception.Message%2A&gt;| Az üzenet honosított hibakarakterlánc. |}&lt;/xref:System.Exception.Message%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="110" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.NotFiniteNumberException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with the invalid number.</source>
          <target state="translated">Egy új példányát inicializálja a <bpt id="p1">&lt;xref href="System.NotFiniteNumberException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> osztály érvénytelen számát.</target>       </trans-unit>
        <trans-unit id="111" translate="yes" xml:space="preserve" extradata="MT">
          <source>The <ph id="ph1">`offendingNumber`</ph> parameter must be both a &lt;xref:System.Double&gt; and an invalid number.</source>
          <target state="translated">A <ph id="ph1">`offendingNumber`</ph> paraméternek kell lennie mind a &lt;xref:System.Double&gt;és száma érvénytelen.&lt;/xref:System.Double&gt;</target>       </trans-unit>
        <trans-unit id="112" translate="yes" xml:space="preserve" extradata="MT">
          <source>The following table shows the initial property values for an instance of &lt;xref:System.NotFiniteNumberException&gt;.</source>
          <target state="translated">Az alábbi táblázat a kezdeti tulajdonságértékek &lt;xref:System.NotFiniteNumberException&gt;.&lt;/xref:System.NotFiniteNumberException&gt; példánya</target>       </trans-unit>
        <trans-unit id="113" translate="yes" xml:space="preserve" extradata="MT">
          <source>|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|A null reference (<ph id="ph1">`Nothing`</ph> in Visual Basic).|   |&lt;xref:System.NotFiniteNumberException.OffendingNumber%2A&gt;|The invalid number.|</source>
          <target state="translated">| Tulajdonság |} Érték |}   |--------------|-----------|   | &lt;xref:System.Exception.InnerException%2A&gt;| Egy null hivatkozás (<ph id="ph1">`Nothing`</ph> a Visual Basic nyelvben). |}   | &lt;xref:System.NotFiniteNumberException.OffendingNumber%2A&gt;| Érvénytelen számú. |}&lt;/xref:System.NotFiniteNumberException.OffendingNumber%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="114" translate="yes" xml:space="preserve">
          <source>The value of the argument that caused the exception.</source>
          <target state="translated">A kivételt okozó argumentum értéke.</target>       </trans-unit>
        <trans-unit id="115" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.NotFiniteNumberException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with a specified error message.</source>
          <target state="translated">Egy új példányát inicializálja a <bpt id="p1">&lt;xref href="System.NotFiniteNumberException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> osztály egy adott hiba miatt.</target>       </trans-unit>
        <trans-unit id="116" translate="yes" xml:space="preserve" extradata="MT">
          <source>Ensure that the <ph id="ph1">`message`</ph> string is understandable to the user and that it is localized for the current culture.</source>
          <target state="translated">Győződjön meg arról, hogy a <ph id="ph1">`message`</ph> karakterlánc érthető, a felhasználó számára, és hogy a jelenlegi kulturális környezethez tartozó honosítva van.</target>       </trans-unit>
        <trans-unit id="117" translate="yes" xml:space="preserve" extradata="MT">
          <source>The following table shows the initial property values for an instance of &lt;xref:System.NotFiniteNumberException&gt;.</source>
          <target state="translated">Az alábbi táblázat a kezdeti tulajdonságértékek &lt;xref:System.NotFiniteNumberException&gt;.&lt;/xref:System.NotFiniteNumberException&gt; példánya</target>       </trans-unit>
        <trans-unit id="118" translate="yes" xml:space="preserve" extradata="MT">
          <source>|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|A null reference (<ph id="ph1">`Nothing`</ph> in Visual Basic).|   |&lt;xref:System.Exception.Message%2A&gt;|The error message string.|</source>
          <target state="translated">| Tulajdonság |} Érték |}   |--------------|-----------|   | &lt;xref:System.Exception.InnerException%2A&gt;| Egy null hivatkozás (<ph id="ph1">`Nothing`</ph> a Visual Basic nyelvben). |}   | &lt;xref:System.Exception.Message%2A&gt;| A üzenetet hiba karakterlánca. |}&lt;/xref:System.Exception.Message%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="119" translate="yes" xml:space="preserve">
          <source>The message that describes the error.</source>
          <target state="translated">Az üzenet, amely leírja a hibát.</target>       </trans-unit>
        <trans-unit id="120" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.NotFiniteNumberException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with serialized data.</source>
          <target state="translated">Egy új példányát inicializálja a <bpt id="p1">&lt;xref href="System.NotFiniteNumberException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> a szerializált adatok osztályt.</target>       </trans-unit>
        <trans-unit id="121" translate="yes" xml:space="preserve" extradata="MT">
          <source>This constructor is called during deserialization to reconstitute the exception object transmitted over a stream.</source>
          <target state="translated">Ez a konstruktor nevezik meglévő kölcsönökre az adatfolyam továbbított kivétel objektum deszerializálása közben.</target>       </trans-unit>
        <trans-unit id="122" translate="yes" xml:space="preserve">
          <source>The object that holds the serialized object data.</source>
          <target state="translated">A szerializált objektum adatokat tartalmazó objektum.</target>       </trans-unit>
        <trans-unit id="123" translate="yes" xml:space="preserve">
          <source>The contextual information about the source or destination.</source>
          <target state="translated">A cél- és környezeti információt.</target>       </trans-unit>
        <trans-unit id="124" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.NotFiniteNumberException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with a specified error message and the invalid number.</source>
          <target state="translated">Egy új példányát inicializálja a <bpt id="p1">&lt;xref href="System.NotFiniteNumberException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> osztály egy adott hibaüzenet és a érvénytelen együtt.</target>       </trans-unit>
        <trans-unit id="125" translate="yes" xml:space="preserve" extradata="MT">
          <source>Ensure that the <ph id="ph1">`message`</ph> string is understandable to the user and that it is localized for the current culture.</source>
          <target state="translated">Győződjön meg arról, hogy a <ph id="ph1">`message`</ph> karakterlánc érthető, a felhasználó számára, és hogy a jelenlegi kulturális környezethez tartozó honosítva van.</target>       </trans-unit>
        <trans-unit id="126" translate="yes" xml:space="preserve" extradata="MT">
          <source>The following table shows the initial property values for an instance of &lt;xref:System.NotFiniteNumberException&gt;.</source>
          <target state="translated">Az alábbi táblázat a kezdeti tulajdonságértékek &lt;xref:System.NotFiniteNumberException&gt;.&lt;/xref:System.NotFiniteNumberException&gt; példánya</target>       </trans-unit>
        <trans-unit id="127" translate="yes" xml:space="preserve" extradata="MT">
          <source>|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|A null reference (<ph id="ph1">`Nothing`</ph> in Visual Basic).|   |&lt;xref:System.Exception.Message%2A&gt;|The error message string.|   |&lt;xref:System.NotFiniteNumberException.OffendingNumber%2A&gt;|The invalid number.|</source>
          <target state="translated">| Tulajdonság |} Érték |}   |--------------|-----------|   | &lt;xref:System.Exception.InnerException%2A&gt;| Egy null hivatkozás (<ph id="ph1">`Nothing`</ph> a Visual Basic nyelvben). |}   | &lt;xref:System.Exception.Message%2A&gt;| A üzenetet hiba karakterlánca. |}   | &lt;xref:System.NotFiniteNumberException.OffendingNumber%2A&gt;| Érvénytelen számú. |}&lt;/xref:System.NotFiniteNumberException.OffendingNumber%2A&gt; &lt;/xref:System.Exception.Message%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="128" translate="yes" xml:space="preserve">
          <source>The message that describes the error.</source>
          <target state="translated">Az üzenet, amely leírja a hibát.</target>       </trans-unit>
        <trans-unit id="129" translate="yes" xml:space="preserve">
          <source>The value of the argument that caused the exception.</source>
          <target state="translated">A kivételt okozó argumentum értéke.</target>       </trans-unit>
        <trans-unit id="130" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.NotFiniteNumberException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with a specified error message and a reference to the inner exception that is root cause of this exception.</source>
          <target state="translated">Egy új példányát inicializálja a <bpt id="p1">&lt;xref href="System.NotFiniteNumberException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> megadott hibaüzenet, és hivatkozni kell a belső kivételben találhatók okozza ezt a kivételt, amely osztály.</target>       </trans-unit>
        <trans-unit id="131" translate="yes" xml:space="preserve" extradata="MT">
          <source>An exception that is thrown as a direct result of a previous exception can include a reference to the previous exception in the &lt;xref:System.Exception.InnerException%2A&gt; property.</source>
          <target state="translated">Kivételt vált ki, mert egy előző kivétel közvetlen eredménye tartalmazhat egy hivatkozást az előző kivétel a &lt;xref:System.Exception.InnerException%2A&gt;tulajdonság.&lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="132" translate="yes" xml:space="preserve" extradata="MT">
          <source>The &lt;xref:System.Exception.InnerException%2A&gt; property returns the same value that is passed into the constructor, or <ph id="ph1">`null`</ph> if the &lt;xref:System.Exception.InnerException%2A&gt; property does not supply the inner exception value to the constructor.</source>
          <target state="translated">A &lt;xref:System.Exception.InnerException%2A&gt;tulajdonság a konstruktornak átadott ugyanazt az értéket adja vissza vagy <ph id="ph1">`null`</ph> Ha a &lt;xref:System.Exception.InnerException%2A&gt;tulajdonság nem adja meg a belső kivétel értékét a konstruktor.&lt;/xref:System.Exception.InnerException%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="133" translate="yes" xml:space="preserve" extradata="MT">
          <source>The following table shows the initial property values for an instance of &lt;xref:System.NotFiniteNumberException&gt;.</source>
          <target state="translated">Az alábbi táblázat a kezdeti tulajdonságértékek &lt;xref:System.NotFiniteNumberException&gt;.&lt;/xref:System.NotFiniteNumberException&gt; példánya</target>       </trans-unit>
        <trans-unit id="134" translate="yes" xml:space="preserve" extradata="MT">
          <source>|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|The inner exception reference.|   |&lt;xref:System.Exception.Message%2A&gt;|The error message string.|</source>
          <target state="translated">| Tulajdonság |} Érték |}   |--------------|-----------|   | &lt;xref:System.Exception.InnerException%2A&gt;| A belső kivétel referencia. |}   | &lt;xref:System.Exception.Message%2A&gt;| A üzenetet hiba karakterlánca. |}&lt;/xref:System.Exception.Message%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="135" translate="yes" xml:space="preserve">
          <source>The error message that explains the reason for the exception.</source>
          <target state="translated">A hibaüzenet, amely ismerteti a kivétel az az oka.</target>       </trans-unit>
        <trans-unit id="136" translate="yes" xml:space="preserve">
          <source>The exception that is the cause of the current exception.</source>
          <target state="translated">A kivétellel, hogy a jelenlegi kivétel okozza.</target>       </trans-unit>
        <trans-unit id="137" translate="yes" xml:space="preserve">
          <source>If the <ph id="ph1">`innerException`</ph> parameter is not a null reference (<bpt id="p1">&lt;xref uid="langword_csharp_Nothing" name="Nothing" href=""&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> in Visual Basic), the current exception is raised in a <bpt id="p2">&lt;xref uid="langword_csharp_catch" name="catch" href=""&gt;</bpt><ept id="p2">&lt;/xref&gt;</ept> block that handles the inner exception.</source>
          <target state="translated">Ha a <ph id="ph1">`innerException`</ph> paraméter nem egy null hivatkozás (<bpt id="p1">&lt;xref uid="langword_csharp_Nothing" name="Nothing" href=""&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> a Visual Basic nyelvben), a jelenlegi kivétel a következik be egy <bpt id="p2">&lt;xref uid="langword_csharp_catch" name="catch" href=""&gt;</bpt> <ept id="p2">&lt;/xref&gt;</ept> blokk, amely kezeli a belső kivételben találhatók.</target>       </trans-unit>
        <trans-unit id="138" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.NotFiniteNumberException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with a specified error message, the invalid number, and a reference to the inner exception that is root cause of this exception.</source>
          <target state="translated">Egy új példányát inicializálja a <bpt id="p1">&lt;xref href="System.NotFiniteNumberException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> megadott hibaüzenet, a érvénytelen, és hivatkozni kell a belső kivételben találhatók okozza ezt a kivételt, amely a osztályt.</target>       </trans-unit>
        <trans-unit id="139" translate="yes" xml:space="preserve" extradata="MT">
          <source>An exception that is thrown as a direct result of a previous exception can include a reference to the previous exception in the &lt;xref:System.Exception.InnerException%2A&gt; property.</source>
          <target state="translated">Kivételt vált ki, mert egy előző kivétel közvetlen eredménye tartalmazhat egy hivatkozást az előző kivétel a &lt;xref:System.Exception.InnerException%2A&gt;tulajdonság.&lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="140" translate="yes" xml:space="preserve" extradata="MT">
          <source>The &lt;xref:System.Exception.InnerException%2A&gt; property returns the same value that is passed into the constructor, or <ph id="ph1">`null`</ph> if the &lt;xref:System.Exception.InnerException%2A&gt; property does not supply the inner exception value to the constructor.</source>
          <target state="translated">A &lt;xref:System.Exception.InnerException%2A&gt;tulajdonság a konstruktornak átadott ugyanazt az értéket adja vissza vagy <ph id="ph1">`null`</ph> Ha a &lt;xref:System.Exception.InnerException%2A&gt;tulajdonság nem adja meg a belső kivétel értékét a konstruktor.&lt;/xref:System.Exception.InnerException%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="141" translate="yes" xml:space="preserve" extradata="MT">
          <source>The following table shows the initial property values for an instance of &lt;xref:System.NotFiniteNumberException&gt;.</source>
          <target state="translated">Az alábbi táblázat a kezdeti tulajdonságértékek &lt;xref:System.NotFiniteNumberException&gt;.&lt;/xref:System.NotFiniteNumberException&gt; példánya</target>       </trans-unit>
        <trans-unit id="142" translate="yes" xml:space="preserve" extradata="MT">
          <source>|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|The inner exception reference.|   |&lt;xref:System.Exception.Message%2A&gt;|The error message string.|   |&lt;xref:System.NotFiniteNumberException.OffendingNumber%2A&gt;|The invalid number.|</source>
          <target state="translated">| Tulajdonság |} Érték |}   |--------------|-----------|   | &lt;xref:System.Exception.InnerException%2A&gt;| A belső kivétel referencia. |}   | &lt;xref:System.Exception.Message%2A&gt;| A üzenetet hiba karakterlánca. |}   | &lt;xref:System.NotFiniteNumberException.OffendingNumber%2A&gt;| Érvénytelen számú. |}&lt;/xref:System.NotFiniteNumberException.OffendingNumber%2A&gt; &lt;/xref:System.Exception.Message%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="143" translate="yes" xml:space="preserve">
          <source>The error message that explains the reason for the exception.</source>
          <target state="translated">A hibaüzenet, amely ismerteti a kivétel az az oka.</target>       </trans-unit>
        <trans-unit id="144" translate="yes" xml:space="preserve">
          <source>The value of the argument that caused the exception.</source>
          <target state="translated">A kivételt okozó argumentum értéke.</target>       </trans-unit>
        <trans-unit id="145" translate="yes" xml:space="preserve">
          <source>The exception that is the cause of the current exception.</source>
          <target state="translated">A kivétellel, hogy a jelenlegi kivétel okozza.</target>       </trans-unit>
        <trans-unit id="146" translate="yes" xml:space="preserve">
          <source>If the <ph id="ph1">`innerException`</ph> parameter is not a null reference (<bpt id="p1">&lt;xref uid="langword_csharp_Nothing" name="Nothing" href=""&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> in Visual Basic), the current exception is raised in a <bpt id="p2">&lt;xref uid="langword_csharp_catch" name="catch" href=""&gt;</bpt><ept id="p2">&lt;/xref&gt;</ept> block that handles the inner exception.</source>
          <target state="translated">Ha a <ph id="ph1">`innerException`</ph> paraméter nem egy null hivatkozás (<bpt id="p1">&lt;xref uid="langword_csharp_Nothing" name="Nothing" href=""&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> a Visual Basic nyelvben), a jelenlegi kivétel a következik be egy <bpt id="p2">&lt;xref uid="langword_csharp_catch" name="catch" href=""&gt;</bpt> <ept id="p2">&lt;/xref&gt;</ept> blokk, amely kezeli a belső kivételben találhatók.</target>       </trans-unit>
        <trans-unit id="147" translate="yes" xml:space="preserve">
          <source>Sets the <bpt id="p1">&lt;xref href="System.Runtime.Serialization.SerializationInfo"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> object with the invalid number and additional exception information.</source>
          <target state="translated">Beállítja a <bpt id="p1">&lt;xref href="System.Runtime.Serialization.SerializationInfo"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> objektum érvénytelen száma és további információ a kivételről.</target>       </trans-unit>
        <trans-unit id="148" translate="yes" xml:space="preserve" extradata="MT">
          <source>&lt;xref:System.TypeLoadException.GetObjectData%2A&gt; sets a &lt;xref:System.Runtime.Serialization.SerializationInfo&gt; with all the exception object data targeted for serialization.</source>
          <target state="translated">&lt;xref:System.TypeLoadException.GetObjectData%2A&gt;Beállítja egy &lt;xref:System.Runtime.Serialization.SerializationInfo&gt;összes kivétel objektum adatokkal szerializálási szánt.&lt;/xref:System.Runtime.Serialization.SerializationInfo&gt;&lt;/xref:System.TypeLoadException.GetObjectData%2A&gt;</target>       </trans-unit>
        <trans-unit id="149" translate="yes" xml:space="preserve" extradata="MT">
          <source>During deserialization, the exception object is reconstituted from the &lt;xref:System.Runtime.Serialization.SerializationInfo&gt; transmitted over the stream.</source>
          <target state="translated">Deszerializálás során, a kivétel objektum előállított a &lt;xref:System.Runtime.Serialization.SerializationInfo&gt;az adatfolyam továbbított.&lt;/xref:System.Runtime.Serialization.SerializationInfo&gt;</target>       </trans-unit>
        <trans-unit id="150" translate="yes" xml:space="preserve" extradata="MT">
          <source>For more information, see &lt;xref:System.Runtime.Serialization.SerializationInfo&gt;.</source>
          <target state="translated">További információkért lásd: &lt;xref:System.Runtime.Serialization.SerializationInfo&gt;.&lt;/xref:System.Runtime.Serialization.SerializationInfo&gt;</target>       </trans-unit>
        <trans-unit id="151" translate="yes" xml:space="preserve">
          <source>The object that holds the serialized object data.</source>
          <target state="translated">A szerializált objektum adatokat tartalmazó objektum.</target>       </trans-unit>
        <trans-unit id="152" translate="yes" xml:space="preserve">
          <source>The contextual information about the source or destination.</source>
          <target state="translated">A cél- és környezeti információt.</target>       </trans-unit>
        <trans-unit id="153" translate="yes" xml:space="preserve">
          <source>The <bpt id="p1">&lt;code&gt;</bpt><ph id="ph1">info</ph><ept id="p1">&lt;/code&gt;</ept> object is <bpt id="p2">&lt;xref uid="langword_csharp_null" name="null" href=""&gt;</bpt><ept id="p2">&lt;/xref&gt;</ept>.</source>
          <target state="translated">The <bpt id="p1">&lt;code&gt;</bpt><ph id="ph1">info</ph><ept id="p1">&lt;/code&gt;</ept> object is <bpt id="p2">&lt;xref uid="langword_csharp_null" name="null" href=""&gt;</bpt><ept id="p2">&lt;/xref&gt;</ept>.</target>       </trans-unit>
        <trans-unit id="154" translate="yes" xml:space="preserve">
          <source>Gets the invalid number that is a positive infinity, a negative infinity, or Not-a-Number (NaN).</source>
          <target state="translated">Lekérdezi a érvénytelen szám, amely egy pozitív végtelen, a negatív végtelent vagy a nem szám (érték NaN).</target>       </trans-unit>
        <trans-unit id="155" translate="yes" xml:space="preserve" extradata="MT">
          <source>The OffendingNumber property returns the same value as was passed into the constructor, or zero if no value was supplied.</source>
          <target state="translated">A OffendingNumber tulajdonság ugyanazt az értéket adja vissza, mert át lett adva a konstruktorban, vagy nulla, ha nincs érték lett megadva.</target>       </trans-unit>
        <trans-unit id="156" translate="yes" xml:space="preserve" extradata="MT">
          <source>Override the OffendingNumber property to customize the content or format of the invalid value.</source>
          <target state="translated">Bírálja felül a OffendingNumber tulajdonság testreszabásához tartalmát vagy az érvénytelen érték formátuma.</target>       </trans-unit>
        <trans-unit id="157" translate="yes" xml:space="preserve" extradata="MT">
          <source>This property is read-only.</source>
          <target state="translated">Ez a tulajdonság csak olvasható.</target>       </trans-unit>
        <trans-unit id="158" translate="yes" xml:space="preserve">
          <source>The invalid number.</source>
          <target state="translated">Érvénytelen a száma.</target>       </trans-unit>
      </group>
    </body>
  </file>
</xliff>