<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">
  <file datatype="xml" original="markdown" source-language="en-US" target-language="zh-tw">
    <header>
      <tool tool-id="mdxliff" tool-name="mdxliff" tool-version="1.0-192e1fd" tool-company="Microsoft" />
      <xliffext:olfilehash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">05177edc37411cc0f0dc7984f7dd2e72975e8654</xliffext:olfilehash>
      <xliffext:olfilepath xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">fulldocset\System.Security.Authentication.InvalidCredentialException.yml</xliffext:olfilepath>
      <xliffext:oltranslationpriority xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">fulldocset</xliffext:oltranslationpriority>
      <xliffext:oltranslationtype xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">Human Translation</xliffext:oltranslationtype>
      <xliffext:olskeletonhash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">53eec4b09537e817181aa857416d36c67e015048</xliffext:olskeletonhash>
      <xliffext:olxliffhash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">99b7e5ca2e629037217c03a8d16f747dffeb9d20</xliffext:olxliffhash>
    </header>
    <body>
      <group id="content" extype="content">
        <trans-unit id="101" translate="yes" xml:space="preserve">
          <source>The exception that is thrown when authentication fails for an authentication stream and cannot be retried.</source>
          <target state="translated">資料流進行驗證的驗證失敗，且無法重試時擲回的例外狀況。</target>       </trans-unit>
        <trans-unit id="102" translate="yes" xml:space="preserve">
          <source>The &lt;xref:System.Net.Security.NegotiateStream&gt; and &lt;xref:System.Net.Security.SslStream&gt; classes throw this exception when authentication fails.</source>
          <target state="translated">&lt;xref:System.Net.Security.NegotiateStream&gt;和&lt;xref:System.Net.Security.SslStream&gt;類別在驗證失敗時，會擲回這個例外狀況。&lt;/xref:System.Net.Security.SslStream&gt; &lt;/xref:System.Net.Security.NegotiateStream&gt;</target>       </trans-unit>
        <trans-unit id="103" translate="yes" xml:space="preserve">
          <source>This exception indicates that the underlying stream is not in a valid state and you cannot retry the authentication using the &lt;xref:System.Net.Security.NegotiateStream&gt; or &lt;xref:System.Net.Security.SslStream&gt; instance.</source>
          <target state="translated">這個例外狀況表示基礎資料流不是處於有效狀態，而且您無法重試驗證使用&lt;xref:System.Net.Security.NegotiateStream&gt;或&lt;xref:System.Net.Security.SslStream&gt;執行個體。&lt;/xref:System.Net.Security.SslStream&gt; &lt;/xref:System.Net.Security.NegotiateStream&gt;</target>       </trans-unit>
        <trans-unit id="104" translate="yes" xml:space="preserve">
          <source>If you can retry the authentication, an &lt;xref:System.Security.Authentication.AuthenticationException&gt; is thrown instead of the InvalidCredentialException.</source>
          <target state="translated">您可以嘗試再次驗證，如果&lt;xref:System.Security.Authentication.AuthenticationException&gt;擲回，而不是 InvalidCredentialException。&lt;/xref:System.Security.Authentication.AuthenticationException&gt;</target>       </trans-unit>
        <trans-unit id="105" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.Security.Authentication.InvalidCredentialException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with no message.</source>
          <target state="translated">初始化的新執行個體<bpt id="p1">&lt;xref href="System.Security.Authentication.InvalidCredentialException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept>類別沒有任何訊息。</target>       </trans-unit>
        <trans-unit id="106" translate="yes" xml:space="preserve">
          <source>This constructor does nothing.</source>
          <target state="translated">這個建構函式沒有任何作用。</target>       </trans-unit>
        <trans-unit id="107" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.Security.Authentication.InvalidCredentialException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with the specified message.</source>
          <target state="translated">初始化的新執行個體<bpt id="p1">&lt;xref href="System.Security.Authentication.InvalidCredentialException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept>類別具有指定的訊息。</target>       </trans-unit>
        <trans-unit id="108" translate="yes" xml:space="preserve">
          <source>This constructor initializes the &lt;xref:System.Exception.Message%2A&gt; property with the text in the <ph id="ph1">`message`</ph> parameter.</source>
          <target state="translated">這個建構函式初始化&lt;xref:System.Exception.Message%2A&gt;屬性中的文字<ph id="ph1">`message`</ph>參數。&lt;/xref:System.Exception.Message%2A&gt;</target>       </trans-unit>
        <trans-unit id="109" translate="yes" xml:space="preserve">
          <source>The &lt;xref:System.Exception.InnerException%2A&gt; property is set to <ph id="ph1">`null`</ph>.</source>
          <target state="translated">&lt;xref:System.Exception.InnerException%2A&gt;屬性設定為<ph id="ph1">`null`</ph>。&lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="110" translate="yes" xml:space="preserve">
          <source>A &lt;xref:System.String&gt; that describes the authentication failure.</source>
          <target state="translated">A&lt;xref:System.String&gt;描述驗證失敗。&lt;/xref:System.String&gt;</target>       </trans-unit>
        <trans-unit id="111" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.Security.Authentication.InvalidCredentialException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class from the specified instances of the <bpt id="p2">&lt;xref href="System.Runtime.Serialization.SerializationInfo"&gt;</bpt><ept id="p2">&lt;/xref&gt;</ept> and &lt;xref:System.Runtime.Serialization.StreamingContext&gt; classes.</source>
          <target state="translated">初始化的新執行個體<bpt id="p1">&lt;xref href="System.Security.Authentication.InvalidCredentialException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept>的指定執行個體從類別<bpt id="p2">&lt;xref href="System.Runtime.Serialization.SerializationInfo"&gt;</bpt><ept id="p2">&lt;/xref&gt;</ept>和&lt;xref:System.Runtime.Serialization.StreamingContext&gt;類別。&lt;/xref:System.Runtime.Serialization.StreamingContext&gt;</target>       </trans-unit>
        <trans-unit id="112" translate="yes" xml:space="preserve">
          <source>A <bpt id="p1">&lt;xref href="System.Runtime.Serialization.SerializationInfo"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> instance that contains the information required to deserialize the new <bpt id="p2">&lt;xref href="System.Security.Authentication.InvalidCredentialException"&gt;</bpt><ept id="p2">&lt;/xref&gt;</ept> instance.</source>
          <target state="translated">A <bpt id="p1">&lt;xref href="System.Runtime.Serialization.SerializationInfo"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept>包含新的還原序列化所需的執行個體<bpt id="p2">&lt;xref href="System.Security.Authentication.InvalidCredentialException"&gt;</bpt><ept id="p2">&lt;/xref&gt;</ept>執行個體。</target>       </trans-unit>
        <trans-unit id="113" translate="yes" xml:space="preserve">
          <source>A &lt;xref:System.Runtime.Serialization.StreamingContext&gt; instance.</source>
          <target state="translated">A&lt;xref:System.Runtime.Serialization.StreamingContext&gt;執行個體。&lt;/xref:System.Runtime.Serialization.StreamingContext&gt;</target>       </trans-unit>
        <trans-unit id="114" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.Security.Authentication.InvalidCredentialException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with the specified message and inner exception.</source>
          <target state="translated">初始化的新執行個體<bpt id="p1">&lt;xref href="System.Security.Authentication.InvalidCredentialException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept>具有指定的訊息和內部例外狀況類別。</target>       </trans-unit>
        <trans-unit id="115" translate="yes" xml:space="preserve">
          <source>This constructor initializes the &lt;xref:System.Exception.Message%2A&gt; property with the text in the <ph id="ph1">`message`</ph> parameter and initializes the &lt;xref:System.Exception.InnerException%2A&gt; property with the <ph id="ph2">`innerException`</ph> parameter value.</source>
          <target state="translated">這個建構函式初始化&lt;xref:System.Exception.Message%2A&gt;屬性中的文字<ph id="ph1">`message`</ph>參數，並初始化&lt;xref:System.Exception.InnerException%2A&gt;屬性<ph id="ph2">`innerException`</ph>參數值。&lt;/xref:System.Exception.InnerException%2A&gt; &lt;/xref:System.Exception.Message%2A&gt;</target>       </trans-unit>
        <trans-unit id="116" translate="yes" xml:space="preserve">
          <source>A &lt;xref:System.String&gt; that describes the authentication failure.</source>
          <target state="translated">A&lt;xref:System.String&gt;描述驗證失敗。&lt;/xref:System.String&gt;</target>       </trans-unit>
        <trans-unit id="117" translate="yes" xml:space="preserve">
          <source>The &lt;xref:System.Exception&gt; that is the cause of the current exception.</source>
          <target state="translated">&lt;xref:System.Exception&gt;也就是造成目前例外狀況。&lt;/xref:System.Exception&gt;</target>       </trans-unit>
      </group>
    </body>
  </file>
</xliff>