<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">
  <file datatype="xml" original="markdown" source-language="en-US" target-language="ko-kr">
    <header>
      <tool tool-id="mdxliff" tool-name="mdxliff" tool-version="1.0-192e1fd" tool-company="Microsoft" />
      <xliffext:olfilehash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">7f95da29a03b46e7f23b3830a1805d5612bc4170</xliffext:olfilehash>
      <xliffext:olfilepath xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">fulldocset\System.Activities.WorkflowApplicationCompletedException.yml</xliffext:olfilepath>
      <xliffext:oltranslationpriority xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">fulldocset</xliffext:oltranslationpriority>
      <xliffext:oltranslationtype xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">Human Translation</xliffext:oltranslationtype>
      <xliffext:olskeletonhash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">fd44ca1afeef64710d899b7892630d1a0c8cebcf</xliffext:olskeletonhash>
      <xliffext:olxliffhash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">28e34ea7ca71155cd587beb53eb200710a30e6b2</xliffext:olxliffhash>
    </header>
    <body>
      <group id="content" extype="content">
        <trans-unit id="101" translate="yes" xml:space="preserve">
          <source>Represents the exception that is thrown when an operation on a workflow instance is not valid because the instance has completed.</source>
          <target state="translated">인스턴스는 완료 되었으므로 워크플로 인스턴스에 대 한 작업이 잘못 된 경우 throw 되는 예외를 나타냅니다.</target>       </trans-unit>
        <trans-unit id="102" translate="yes" xml:space="preserve">
          <source>Creates a new instance of the <bpt id="p1">&lt;xref href="System.Activities.WorkflowApplicationCompletedException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class.</source>
          <target state="translated">새 인스턴스를 만듭니다는 <bpt id="p1">&lt;xref href="System.Activities.WorkflowApplicationCompletedException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> 클래스입니다.</target>       </trans-unit>
        <trans-unit id="103" translate="yes" xml:space="preserve">
          <source>Creates a new instance of the <bpt id="p1">&lt;xref href="System.Activities.WorkflowApplicationCompletedException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with a text string description of the exception.</source>
          <target state="translated">새 인스턴스를 만듭니다는 <bpt id="p1">&lt;xref href="System.Activities.WorkflowApplicationCompletedException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> 클래스 예외에 대 한 텍스트 문자열 설명입니다.</target>       </trans-unit>
        <trans-unit id="104" translate="yes" xml:space="preserve">
          <source>A description of the application completed exception.</source>
          <target state="translated">응용 프로그램에 대 한 설명을 완료 된 예외입니다.</target>       </trans-unit>
        <trans-unit id="105" translate="yes" xml:space="preserve">
          <source>Creates a new instance of the <bpt id="p1">&lt;xref href="System.Activities.WorkflowApplicationCompletedException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with the context and serialization information required to retrieve data about this exception from a serialized stream.</source>
          <target state="translated">새 인스턴스를 만듭니다는 <bpt id="p1">&lt;xref href="System.Activities.WorkflowApplicationCompletedException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> serialize 된 스트림에서이 예외에 대 한 데이터를 검색 하는 데 필요한 컨텍스트 및 serialization 정보를 사용 하 여 클래스입니다.</target>       </trans-unit>
        <trans-unit id="106" translate="yes" xml:space="preserve">
          <source>All the information required to serialize or deserialize the application completed exception object.</source>
          <target state="translated">Serialize 하거나 응용 프로그램이 완료 된 예외 개체를 deserialize 하는 데 필요한 모든 정보입니다.</target>       </trans-unit>
        <trans-unit id="107" translate="yes" xml:space="preserve">
          <source>The source and destination of a given serialized stream and an additional caller-defined context.</source>
          <target state="translated">원본과 지정한 직렬화 된 스트림의 대상과 추가 호출자 정의 컨텍스트입니다.</target>       </trans-unit>
        <trans-unit id="108" translate="yes" xml:space="preserve">
          <source>Creates a new instance of the <bpt id="p1">&lt;xref href="System.Activities.WorkflowApplicationCompletedException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with a text string description of the exception and with an additional exception that is the cause of the application completed exception.</source>
          <target state="translated">새 인스턴스를 만듭니다는 <bpt id="p1">&lt;xref href="System.Activities.WorkflowApplicationCompletedException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> 클래스 예외에 대 한 텍스트 문자열 설명 및 응용 프로그램이 완료 된 예외의 원인이 되는 추가 예외를 사용 합니다.</target>       </trans-unit>
        <trans-unit id="109" translate="yes" xml:space="preserve">
          <source>A description of the application completed exception.</source>
          <target state="translated">응용 프로그램에 대 한 설명을 완료 된 예외입니다.</target>       </trans-unit>
        <trans-unit id="110" translate="yes" xml:space="preserve">
          <source>An exception that has a causal relationship to the application completed exception.</source>
          <target state="translated">완료 된 예외를 예외와 인과 관계를 응용 프로그램입니다.</target>       </trans-unit>
        <trans-unit id="111" translate="yes" xml:space="preserve">
          <source>The application completed exception is thrown in response to the inner exception and can use information from the inner exception to handle the error more appropriately.</source>
          <target state="translated">응용 프로그램이 완료 된 예외는 내부 예외에 대 한 응답으로 발생 하 고 오류를 보다 적절 하 게 처리에 내부 예외의 정보를에서 사용할 수 있습니다.</target>       </trans-unit>
        <trans-unit id="112" translate="yes" xml:space="preserve">
          <source>Creates a new instance of the <bpt id="p1">&lt;xref href="System.Activities.WorkflowApplicationCompletedException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with a text string description of the exception and with a unique identifier for the exception.</source>
          <target state="translated">새 인스턴스를 만듭니다는 <bpt id="p1">&lt;xref href="System.Activities.WorkflowApplicationCompletedException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> 클래스 예외에 대 한 텍스트 문자열 설명 및 예외에 대 한 고유 식별자를 사용 합니다.</target>       </trans-unit>
        <trans-unit id="113" translate="yes" xml:space="preserve">
          <source>A description of the application completed exception.</source>
          <target state="translated">응용 프로그램에 대 한 설명을 완료 된 예외입니다.</target>       </trans-unit>
        <trans-unit id="114" translate="yes" xml:space="preserve">
          <source>A globally unique identifier.</source>
          <target state="translated">전역 고유 식별자입니다.</target>       </trans-unit>
        <trans-unit id="115" translate="yes" xml:space="preserve">
          <source>Creates a new instance of the <bpt id="p1">&lt;xref href="System.Activities.WorkflowApplicationCompletedException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with a text string description of the exception, a unique identifier for it, and an additional exception that is the cause of the application completed exception.</source>
          <target state="translated">새 인스턴스를 만듭니다는 <bpt id="p1">&lt;xref href="System.Activities.WorkflowApplicationCompletedException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> 예외,에 대 한 고유 식별자 및 응용 프로그램이 완료 된 예외의 원인이 되는 추가 예외 클래스에 대 한 텍스트 문자열 설명입니다.</target>       </trans-unit>
        <trans-unit id="116" translate="yes" xml:space="preserve">
          <source>A description of the application completed exception.</source>
          <target state="translated">응용 프로그램에 대 한 설명을 완료 된 예외입니다.</target>       </trans-unit>
        <trans-unit id="117" translate="yes" xml:space="preserve">
          <source>A globally unique identifier.</source>
          <target state="translated">전역 고유 식별자입니다.</target>       </trans-unit>
        <trans-unit id="118" translate="yes" xml:space="preserve">
          <source>An exception that has a causal relationship to the application completed exception.</source>
          <target state="translated">완료 된 예외를 예외와 인과 관계를 응용 프로그램입니다.</target>       </trans-unit>
        <trans-unit id="119" translate="yes" xml:space="preserve">
          <source>The application completed exception is thrown in response to the inner exception and can use information from the inner exception to handle the error more appropriately.</source>
          <target state="translated">응용 프로그램이 완료 된 예외는 내부 예외에 대 한 응답으로 발생 하 고 오류를 보다 적절 하 게 처리에 내부 예외의 정보를에서 사용할 수 있습니다.</target>       </trans-unit>
      </group>
    </body>
  </file>
</xliff>