<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">
  <file datatype="xml" original="markdown" source-language="en-US" target-language="ko-kr">
    <header>
      <tool tool-id="mdxliff" tool-name="mdxliff" tool-version="1.0-192e1fd" tool-company="Microsoft" />
      <xliffext:olfilehash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">691f9b9e1fcf24dd544d6fcae768f4dd0d552a7f</xliffext:olfilehash>
      <xliffext:olfilepath xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">fulldocset\System.Security.XmlSyntaxException.yml</xliffext:olfilepath>
      <xliffext:oltranslationpriority xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">fulldocset</xliffext:oltranslationpriority>
      <xliffext:oltranslationtype xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">Human Translation</xliffext:oltranslationtype>
      <xliffext:olskeletonhash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">71758f2f5230cc08a2b8069736252c1156abd49b</xliffext:olskeletonhash>
      <xliffext:olxliffhash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">2011bdc7a034477702ccc3789accf6aadc220b30</xliffext:olxliffhash>
    </header>
    <body>
      <group id="content" extype="content">
        <trans-unit id="101" translate="yes" xml:space="preserve">
          <source>The exception that is thrown when there is a syntax error in XML parsing.</source>
          <target state="translated">XML 구문 분석에 구문 오류가 있을 때 throw 되는 예외입니다.</target>       </trans-unit>
        <trans-unit id="102" translate="yes" xml:space="preserve">
          <source>This class cannot be inherited.</source>
          <target state="translated">이 클래스는 상속 될 수 없습니다.</target>       </trans-unit>
        <trans-unit id="103" translate="yes" xml:space="preserve" extradata="MT">
          <source>XmlSyntaxException uses the default &lt;xref:System.Object.Equals%2A&gt; implementation, which supports reference equality.</source>
          <target state="translated">기본값을 사용 하 여 XmlSyntaxException &lt;xref:System.Object.Equals%2A&gt;구현을 참조 일치를 지원 합니다.&lt;/xref:System.Object.Equals%2A&gt;</target>       </trans-unit>
        <trans-unit id="104" translate="yes" xml:space="preserve" extradata="MT">
          <source>For a list of initial property values for an instance of XmlSyntaxException, see the constructor.</source>
          <target state="translated">목록이 XmlSyntaxException의 인스턴스에 대 한 초기 속성 값에 대 한 생성자를 참조 하십시오.</target>       </trans-unit>
        <trans-unit id="105" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.Security.XmlSyntaxException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with default properties.</source>
          <target state="translated">새 인스턴스를 초기화는 <bpt id="p1">&lt;xref href="System.Security.XmlSyntaxException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> 클래스 기본 속성을 사용 합니다.</target>       </trans-unit>
        <trans-unit id="106" translate="yes" xml:space="preserve" extradata="MT">
          <source>The following table shows the initial property values for an instance of &lt;xref:System.Security.XmlSyntaxException&gt;.</source>
          <target state="translated">다음 표에서 &lt;xref:System.Security.XmlSyntaxException&gt;안내 하십시오.&lt;/xref:System.Security.XmlSyntaxException&gt; 인스턴스에 대 한 초기 속성 값을 보여 줍니다.</target>       </trans-unit>
        <trans-unit id="107" translate="yes" xml:space="preserve" extradata="MT">
          <source>|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|<ph id="ph1">`null`</ph>.|   |&lt;xref:System.Exception.Message%2A&gt;|"Invalid syntax."|</source>
          <target state="translated">| 속성 | 값 |   |--------------|-----------|   | &lt;xref:System.Exception.InnerException%2A&gt;| <ph id="ph1">`null`</ph>.|   | &lt;xref:System.Exception.Message%2A&gt;|" 구문이 잘못 되었습니다. "|&lt;/xref:System.Exception.Message%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="108" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.Security.XmlSyntaxException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with the line number where the exception was detected.</source>
          <target state="translated">새 인스턴스를 초기화는 <bpt id="p1">&lt;xref href="System.Security.XmlSyntaxException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> 예외가 발견 된 줄 번호를 사용 하 여 클래스입니다.</target>       </trans-unit>
        <trans-unit id="109" translate="yes" xml:space="preserve" extradata="MT">
          <source>The line number of an XML stream is updated whenever a newline character is detected.</source>
          <target state="translated">XML 스트림의 줄 번호는 줄 바꿈 문자가 발견 될 때마다 업데이트 됩니다.</target>       </trans-unit>
        <trans-unit id="110" translate="yes" xml:space="preserve" extradata="MT">
          <source>Numbering begins with 1 for the first line.</source>
          <target state="translated">번호는 첫 번째 줄에 대해 1로 시작합니다.</target>       </trans-unit>
        <trans-unit id="111" translate="yes" xml:space="preserve" extradata="MT">
          <source>The following table shows the initial property values for an instance of &lt;xref:System.Security.XmlSyntaxException&gt;.</source>
          <target state="translated">다음 표에서 &lt;xref:System.Security.XmlSyntaxException&gt;안내 하십시오.&lt;/xref:System.Security.XmlSyntaxException&gt; 인스턴스에 대 한 초기 속성 값을 보여 줍니다.</target>       </trans-unit>
        <trans-unit id="112" translate="yes" xml:space="preserve" extradata="MT">
          <source>|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|<ph id="ph1">`null`</ph>.|   |&lt;xref:System.Exception.Message%2A&gt;|"Invalid syntax on line <ph id="ph2">`lineNumber`</ph>."|</source>
          <target state="translated">| 속성 | 값 |   |--------------|-----------|   | &lt;xref:System.Exception.InnerException%2A&gt;| <ph id="ph1">`null`</ph>.|   | &lt;xref:System.Exception.Message%2A&gt;|" 줄에 잘못 된 구문이 <ph id="ph2">`lineNumber`</ph>. "|&lt;/xref:System.Exception.Message%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="113" translate="yes" xml:space="preserve">
          <source>The line number of the XML stream where the XML syntax error was detected.</source>
          <target state="translated">XML 구문 오류가 검색 되었습니다 XML 스트림의 줄 번호입니다.</target>       </trans-unit>
        <trans-unit id="114" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.Security.XmlSyntaxException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with a specified error message.</source>
          <target state="translated">새 인스턴스를 초기화는 <bpt id="p1">&lt;xref href="System.Security.XmlSyntaxException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> 지정된 된 오류 메시지를 사용 하 여 클래스입니다.</target>       </trans-unit>
        <trans-unit id="115" translate="yes" xml:space="preserve" extradata="MT">
          <source>The following table shows the initial property values for an instance of &lt;xref:System.Security.XmlSyntaxException&gt;.</source>
          <target state="translated">다음 표에서 &lt;xref:System.Security.XmlSyntaxException&gt;안내 하십시오.&lt;/xref:System.Security.XmlSyntaxException&gt; 인스턴스에 대 한 초기 속성 값을 보여 줍니다.</target>       </trans-unit>
        <trans-unit id="116" translate="yes" xml:space="preserve" extradata="MT">
          <source>|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|<ph id="ph1">`null`</ph>.|   |&lt;xref:System.Exception.Message%2A&gt;|The error message string.|</source>
          <target state="translated">| 속성 | 값 |   |--------------|-----------|   | &lt;xref:System.Exception.InnerException%2A&gt;| <ph id="ph1">`null`</ph>.|   | &lt;xref:System.Exception.Message%2A&gt;| 오류 메시지 문자열입니다. |&lt;/xref:System.Exception.Message%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="117" translate="yes" xml:space="preserve">
          <source>The error message that explains the reason for the exception.</source>
          <target state="translated">예외에 대 한 이유를 설명 하는 오류 메시지입니다.</target>       </trans-unit>
        <trans-unit id="118" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.Security.XmlSyntaxException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with a specified error message and the line number where the exception was detected.</source>
          <target state="translated">새 인스턴스를 초기화는 <bpt id="p1">&lt;xref href="System.Security.XmlSyntaxException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> 된 지정된 된 오류 메시지 및 예외가 발견 된 줄 번호입니다.</target>       </trans-unit>
        <trans-unit id="119" translate="yes" xml:space="preserve" extradata="MT">
          <source>The line number of an XML stream is updated whenever a newline character is detected.</source>
          <target state="translated">XML 스트림의 줄 번호는 줄 바꿈 문자가 발견 될 때마다 업데이트 됩니다.</target>       </trans-unit>
        <trans-unit id="120" translate="yes" xml:space="preserve" extradata="MT">
          <source>Numbering begins with 1 for the first line.</source>
          <target state="translated">번호는 첫 번째 줄에 대해 1로 시작합니다.</target>       </trans-unit>
        <trans-unit id="121" translate="yes" xml:space="preserve" extradata="MT">
          <source>The following table shows the initial property values for an instance of &lt;xref:System.Security.XmlSyntaxException&gt;.</source>
          <target state="translated">다음 표에서 &lt;xref:System.Security.XmlSyntaxException&gt;안내 하십시오.&lt;/xref:System.Security.XmlSyntaxException&gt; 인스턴스에 대 한 초기 속성 값을 보여 줍니다.</target>       </trans-unit>
        <trans-unit id="122" translate="yes" xml:space="preserve" extradata="MT">
          <source>|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|<ph id="ph1">`null`</ph>.|   |&lt;xref:System.Exception.Message%2A&gt;|"Invalid syntax on line <ph id="ph2">`lineNumber`</ph><ph id="ph3"> - </ph><ph id="ph4">`message`</ph> "|</source>
          <target state="translated">| 속성 | 값 |   |--------------|-----------|   | &lt;xref:System.Exception.InnerException%2A&gt;| <ph id="ph1">`null`</ph>.|   | &lt;xref:System.Exception.Message%2A&gt;|" 줄에 잘못 된 구문이 <ph id="ph2">`lineNumber`</ph> <ph id="ph3"> - </ph> <ph id="ph4">`message`</ph> "|&lt;/xref:System.Exception.Message%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="123" translate="yes" xml:space="preserve">
          <source>The line number of the XML stream where the XML syntax error was detected.</source>
          <target state="translated">XML 구문 오류가 검색 되었습니다 XML 스트림의 줄 번호입니다.</target>       </trans-unit>
        <trans-unit id="124" translate="yes" xml:space="preserve">
          <source>The error message that explains the reason for the exception.</source>
          <target state="translated">예외에 대 한 이유를 설명 하는 오류 메시지입니다.</target>       </trans-unit>
        <trans-unit id="125" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.Security.XmlSyntaxException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with a specified error message and a reference to the inner exception that is the cause of this exception.</source>
          <target state="translated">새 인스턴스를 초기화는 <bpt id="p1">&lt;xref href="System.Security.XmlSyntaxException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> 지정된 된 오류 메시지와 해당 예외의 원인인 내부 예외에 대 한 참조를 사용 하 여 클래스입니다.</target>       </trans-unit>
        <trans-unit id="126" translate="yes" xml:space="preserve" extradata="MT">
          <source>An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the &lt;xref:System.Exception.InnerException%2A&gt; property.</source>
          <target state="translated">이전 예외의 직접적인 결과에 이전 예외에 대 한 참조가 들어 있어야 throw 되는 예외는 &lt;xref:System.Exception.InnerException%2A&gt;속성.&lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="127" translate="yes" xml:space="preserve" extradata="MT">
          <source>The &lt;xref:System.Exception.InnerException%2A&gt; property returns the same value that is passed into the constructor, or <ph id="ph1">`null`</ph> if the &lt;xref:System.Exception.InnerException%2A&gt; property does not supply the inner exception value to the constructor.</source>
          <target state="translated">&lt;xref:System.Exception.InnerException%2A&gt;속성은 생성자에 전달 되는 동일한 값을 반환 하거나 <ph id="ph1">`null`</ph> 경우는 &lt;xref:System.Exception.InnerException%2A&gt;생성자에 내부 예외 값을 제공 하지 않는.&lt;/xref:System.Exception.InnerException%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="128" translate="yes" xml:space="preserve" extradata="MT">
          <source>The following table shows the initial property values for an instance of &lt;xref:System.Security.XmlSyntaxException&gt;.</source>
          <target state="translated">다음 표에서 &lt;xref:System.Security.XmlSyntaxException&gt;안내 하십시오.&lt;/xref:System.Security.XmlSyntaxException&gt; 인스턴스에 대 한 초기 속성 값을 보여 줍니다.</target>       </trans-unit>
        <trans-unit id="129" translate="yes" xml:space="preserve" extradata="MT">
          <source>|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|The inner exception reference.|   |&lt;xref:System.Exception.Message%2A&gt;|The error message string.|</source>
          <target state="translated">| 속성 | 값 |   |--------------|-----------|   | &lt;xref:System.Exception.InnerException%2A&gt;| 내부 예외를 참조 합니다. |   | &lt;xref:System.Exception.Message%2A&gt;| 오류 메시지 문자열입니다. |&lt;/xref:System.Exception.Message%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="130" translate="yes" xml:space="preserve">
          <source>The error message that explains the reason for the exception.</source>
          <target state="translated">예외에 대 한 이유를 설명 하는 오류 메시지입니다.</target>       </trans-unit>
        <trans-unit id="131" translate="yes" xml:space="preserve">
          <source>The exception that is the cause of the current exception.</source>
          <target state="translated">현재 예외의 원인인 예외입니다.</target>       </trans-unit>
        <trans-unit id="132" translate="yes" xml:space="preserve">
          <source>If the <ph id="ph1">`inner`</ph> parameter is not <bpt id="p1">&lt;xref uid="langword_csharp_null" name="null" href=""&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept>, the current exception is raised in a <bpt id="p2">&lt;xref uid="langword_csharp_catch" name="catch" href=""&gt;</bpt><ept id="p2">&lt;/xref&gt;</ept> block that handles the inner exception.</source>
          <target state="translated">경우는 <ph id="ph1">`inner`</ph> 매개 변수가 않습니다 <bpt id="p1">&lt;xref uid="langword_csharp_null" name="null" href=""&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept>에서 현재 예외가 발생 한 <bpt id="p2">&lt;xref uid="langword_csharp_catch" name="catch" href=""&gt;</bpt> <ept id="p2">&lt;/xref&gt;</ept> 내부 예외를 처리 하는 블록입니다.</target>       </trans-unit>
      </group>
    </body>
  </file>
</xliff>