<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">
  <file datatype="xml" original="markdown" source-language="en-US" target-language="ko-kr">
    <header>
      <tool tool-id="mdxliff" tool-name="mdxliff" tool-version="1.0-192e1fd" tool-company="Microsoft" />
      <xliffext:olfilehash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">9262cd6549f564f0bcc49c7150213f621b9bad3d</xliffext:olfilehash>
      <xliffext:olfilepath xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">fulldocset\System.Workflow.ComponentModel.Serialization.WorkflowMarkupSerializationException.yml</xliffext:olfilepath>
      <xliffext:oltranslationpriority xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">fulldocset</xliffext:oltranslationpriority>
      <xliffext:oltranslationtype xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">Human Translation</xliffext:oltranslationtype>
      <xliffext:olskeletonhash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">6cef3f0660e20e56b89aa2eebe0a08d0e66f33a8</xliffext:olskeletonhash>
      <xliffext:olxliffhash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">e5bee60a261b0661b9e5da0d1cf9852a9f6624fa</xliffext:olxliffhash>
    </header>
    <body>
      <group id="content" extype="content">
        <trans-unit id="101" translate="yes" xml:space="preserve">
          <source>The exception that is thrown by methods that perform serialization and deserialization.</source>
          <target state="translated">Serialization 및 deserialization을 수행 하는 메서드에서 throw 되는 예외입니다.</target>       </trans-unit>
        <trans-unit id="102" translate="yes" xml:space="preserve" extradata="MT">
          <source><ph id="ph1">&gt; [!NOTE]</ph><ph id="ph2"> &gt;  </ph><ph id="ph3">[!INCLUDE[DeprecatedContent](~/add/includes/ajax-current-ext-md.md)]</ph>       WorkflowMarkupSerializationException includes information about the line and column locations that caused the exception to be thrown.</source>
          <target state="translated"><ph id="ph1">&gt; [!NOTE]</ph><ph id="ph2"> &gt;  </ph><ph id="ph3">[!INCLUDE[DeprecatedContent](~/add/includes/ajax-current-ext-md.md)]</ph>WorkflowMarkupSerializationException 예외를 throw 하는 줄 및 열 위치에 대 한 정보를 포함 합니다.</target>       </trans-unit>
        <trans-unit id="103" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.Workflow.ComponentModel.Serialization.WorkflowMarkupSerializationException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class.</source>
          <target state="translated">새 인스턴스를 초기화는 <bpt id="p1">&lt;xref href="System.Workflow.ComponentModel.Serialization.WorkflowMarkupSerializationException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> 클래스입니다.</target>       </trans-unit>
        <trans-unit id="104" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.Workflow.ComponentModel.Serialization.WorkflowMarkupSerializationException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class by using the specified error message.</source>
          <target state="translated">새 인스턴스를 초기화는 <bpt id="p1">&lt;xref href="System.Workflow.ComponentModel.Serialization.WorkflowMarkupSerializationException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> 지정된 된 오류 메시지를 사용 하 여 클래스입니다.</target>       </trans-unit>
        <trans-unit id="105" translate="yes" xml:space="preserve">
          <source>A string that contains message that describes the error.</source>
          <target state="translated">오류를 설명 하는 메시지를 포함 하는 문자열입니다.</target>       </trans-unit>
        <trans-unit id="106" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.Workflow.ComponentModel.Serialization.WorkflowMarkupSerializationException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class by using serialized data.</source>
          <target state="translated">새 인스턴스를 초기화는 <bpt id="p1">&lt;xref href="System.Workflow.ComponentModel.Serialization.WorkflowMarkupSerializationException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> 클래스를 사용 하 여 serialize 된 데이터입니다.</target>       </trans-unit>
        <trans-unit id="107" translate="yes" xml:space="preserve">
          <source>A <bpt id="p1">&lt;xref href="System.Runtime.Serialization.SerializationInfo"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> that contains the serialized object data about the <bpt id="p2">&lt;xref href="System.Workflow.ComponentModel.Serialization.WorkflowMarkupSerializationException"&gt;</bpt><ept id="p2">&lt;/xref&gt;</ept> being thrown.</source>
          <target state="translated">A <bpt id="p1">&lt;xref href="System.Runtime.Serialization.SerializationInfo"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> 에 대 한 직렬화 된 개체 데이터를 포함 하는 <bpt id="p2">&lt;xref href="System.Workflow.ComponentModel.Serialization.WorkflowMarkupSerializationException"&gt;</bpt> <ept id="p2">&lt;/xref&gt;</ept> throw 합니다.</target>       </trans-unit>
        <trans-unit id="108" translate="yes" xml:space="preserve">
          <source>A &lt;xref:System.Runtime.Serialization.StreamingContext&gt; that contains the context information about the source or destination of the bits the serializer was using.</source>
          <target state="translated">A &lt;xref:System.Runtime.Serialization.StreamingContext&gt;소스 또는 대상 serializer에서 사용한 비트에 대 한 컨텍스트 정보를 포함 하는.&lt;/xref:System.Runtime.Serialization.StreamingContext&gt;</target>       </trans-unit>
        <trans-unit id="109" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.Workflow.ComponentModel.Serialization.WorkflowMarkupSerializationException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class by using an error message and an exception.</source>
          <target state="translated">새 인스턴스를 초기화는 <bpt id="p1">&lt;xref href="System.Workflow.ComponentModel.Serialization.WorkflowMarkupSerializationException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> 오류 메시지와 예외를 사용 하 여 클래스입니다.</target>       </trans-unit>
        <trans-unit id="110" translate="yes" xml:space="preserve">
          <source>A string that contains message that describes the error.</source>
          <target state="translated">오류를 설명 하는 메시지를 포함 하는 문자열입니다.</target>       </trans-unit>
        <trans-unit id="111" translate="yes" xml:space="preserve">
          <source>The exception that is the cause of the <bpt id="p1">&lt;xref href="System.Workflow.ComponentModel.Serialization.WorkflowMarkupSerializationException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept>.</source>
          <target state="translated">원인이 되는 예외는 <bpt id="p1">&lt;xref href="System.Workflow.ComponentModel.Serialization.WorkflowMarkupSerializationException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept>합니다.</target>       </trans-unit>
        <trans-unit id="112" translate="yes" xml:space="preserve">
          <source>If <ph id="ph1">`innerException`</ph> is not a null reference (<bpt id="p1">&lt;xref uid="langword_csharp_Nothing" name="Nothing" href=""&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> in Visual Basic), the current exception is raised in a catch block that handles the inner exception.</source>
          <target state="translated">경우 <ph id="ph1">`innerException`</ph> 은 null 참조 (<bpt id="p1">&lt;xref uid="langword_csharp_Nothing" name="Nothing" href=""&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> Visual basic에서), 현재 예외는 내부 예외를 처리 하는 catch 블록에서 발생 합니다.</target>       </trans-unit>
        <trans-unit id="113" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.Workflow.ComponentModel.Serialization.WorkflowMarkupSerializationException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class by using an error message and the line and column numbers that caused the exception to be thrown.</source>
          <target state="translated">새 인스턴스를 초기화는 <bpt id="p1">&lt;xref href="System.Workflow.ComponentModel.Serialization.WorkflowMarkupSerializationException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> 오류 메시지와 예외를 throw 한 줄 및 열 번호를 사용 하 여 클래스입니다.</target>       </trans-unit>
        <trans-unit id="114" translate="yes" xml:space="preserve">
          <source>A string that contains message that describes the error.</source>
          <target state="translated">오류를 설명 하는 메시지를 포함 하는 문자열입니다.</target>       </trans-unit>
        <trans-unit id="115" translate="yes" xml:space="preserve">
          <source>The line number in the object or XOML file that caused the exception to be thrown.</source>
          <target state="translated">개체 또는 예외를 throw XOML 파일의 줄 번호입니다.</target>       </trans-unit>
        <trans-unit id="116" translate="yes" xml:space="preserve">
          <source>The column position in the object or XOML file that caused the exception to be thrown.</source>
          <target state="translated">개체 또는 예외를 throw XOML 파일의 열 위치입니다.</target>       </trans-unit>
        <trans-unit id="117" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.Workflow.ComponentModel.Serialization.WorkflowMarkupSerializationException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class by using an error message, an exception, and the line and column numbers that caused the exception to be thrown.</source>
          <target state="translated">새 인스턴스를 초기화는 <bpt id="p1">&lt;xref href="System.Workflow.ComponentModel.Serialization.WorkflowMarkupSerializationException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> 오류 메시지, 예외 및 예외를 throw 한 줄 및 열 번호를 사용 하 여 클래스입니다.</target>       </trans-unit>
        <trans-unit id="118" translate="yes" xml:space="preserve">
          <source>A string that contains message that describes the error.</source>
          <target state="translated">오류를 설명 하는 메시지를 포함 하는 문자열입니다.</target>       </trans-unit>
        <trans-unit id="119" translate="yes" xml:space="preserve">
          <source>The exception that is the cause of the <bpt id="p1">&lt;xref href="System.Workflow.ComponentModel.Serialization.WorkflowMarkupSerializationException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept>.</source>
          <target state="translated">원인이 되는 예외는 <bpt id="p1">&lt;xref href="System.Workflow.ComponentModel.Serialization.WorkflowMarkupSerializationException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept>합니다.</target>       </trans-unit>
        <trans-unit id="120" translate="yes" xml:space="preserve">
          <source>If <ph id="ph1">`innerException`</ph> is not a null reference (<bpt id="p1">&lt;xref uid="langword_csharp_Nothing" name="Nothing" href=""&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> in Visual Basic), the current exception is raised in a catch block that handles the inner exception.</source>
          <target state="translated">경우 <ph id="ph1">`innerException`</ph> 은 null 참조 (<bpt id="p1">&lt;xref uid="langword_csharp_Nothing" name="Nothing" href=""&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> Visual basic에서), 현재 예외는 내부 예외를 처리 하는 catch 블록에서 발생 합니다.</target>       </trans-unit>
        <trans-unit id="121" translate="yes" xml:space="preserve">
          <source>The line number in the object or XOML file that caused the exception to be thrown.</source>
          <target state="translated">개체 또는 예외를 throw XOML 파일의 줄 번호입니다.</target>       </trans-unit>
        <trans-unit id="122" translate="yes" xml:space="preserve">
          <source>The column position in the object or XOML file that caused the exception to be thrown.</source>
          <target state="translated">개체 또는 예외를 throw XOML 파일의 열 위치입니다.</target>       </trans-unit>
        <trans-unit id="123" translate="yes" xml:space="preserve">
          <source>Sets the specified <bpt id="p1">&lt;xref href="System.Runtime.Serialization.SerializationInfo"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> with information about the <bpt id="p2">&lt;xref href="System.Workflow.ComponentModel.Serialization.WorkflowMarkupSerializationException"&gt;</bpt><ept id="p2">&lt;/xref&gt;</ept>.</source>
          <target state="translated">지정 된 <bpt id="p1">&lt;xref href="System.Runtime.Serialization.SerializationInfo"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> 에 대 한 정보는 <bpt id="p2">&lt;xref href="System.Workflow.ComponentModel.Serialization.WorkflowMarkupSerializationException"&gt;</bpt> <ept id="p2">&lt;/xref&gt;</ept>합니다.</target>       </trans-unit>
        <trans-unit id="124" translate="yes" xml:space="preserve" extradata="MT">
          <source>GetObjectData sets a &lt;xref:System.Runtime.Serialization.SerializationInfo&gt; with all the exception object data targeted for serialization.</source>
          <target state="translated">GetObjectData 집합은 &lt;xref:System.Runtime.Serialization.SerializationInfo&gt;serialization 대상인 모든 예외 개체 데이터가.&lt;/xref:System.Runtime.Serialization.SerializationInfo&gt;</target>       </trans-unit>
        <trans-unit id="125" translate="yes" xml:space="preserve" extradata="MT">
          <source>During de-serialization, the exception is reconstituted from the &lt;xref:System.Runtime.Serialization.SerializationInfo&gt; transmitted over the stream.</source>
          <target state="translated">deserialization을 하는 동안 예외가 재구성 됩니다는 &lt;xref:System.Runtime.Serialization.SerializationInfo&gt;스트림을 통해 전송 된.&lt;/xref:System.Runtime.Serialization.SerializationInfo&gt;</target>       </trans-unit>
        <trans-unit id="126" translate="yes" xml:space="preserve">
          <source>A <bpt id="p1">&lt;xref href="System.Runtime.Serialization.SerializationInfo"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> that contains the serialized object data about the <bpt id="p2">&lt;xref href="System.Workflow.ComponentModel.Serialization.WorkflowMarkupSerializationException"&gt;</bpt><ept id="p2">&lt;/xref&gt;</ept> being thrown.</source>
          <target state="translated">A <bpt id="p1">&lt;xref href="System.Runtime.Serialization.SerializationInfo"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> 에 대 한 직렬화 된 개체 데이터를 포함 하는 <bpt id="p2">&lt;xref href="System.Workflow.ComponentModel.Serialization.WorkflowMarkupSerializationException"&gt;</bpt> <ept id="p2">&lt;/xref&gt;</ept> throw 합니다.</target>       </trans-unit>
        <trans-unit id="127" translate="yes" xml:space="preserve">
          <source>A &lt;xref:System.Runtime.Serialization.StreamingContext&gt; that contains the context information about the source or destination of the bits the serializer was using.</source>
          <target state="translated">A &lt;xref:System.Runtime.Serialization.StreamingContext&gt;소스 또는 대상 serializer에서 사용한 비트에 대 한 컨텍스트 정보를 포함 하는.&lt;/xref:System.Runtime.Serialization.StreamingContext&gt;</target>       </trans-unit>
        <trans-unit id="128" translate="yes" xml:space="preserve">
          <source>Gets the line number in the object or XOML file that caused the exception to be thrown.</source>
          <target state="translated">개체 또는 예외를 throw XOML 파일의 줄 번호를 가져옵니다.</target>       </trans-unit>
        <trans-unit id="129" translate="yes" xml:space="preserve">
          <source>An integer that represents the line number on which the exception was thrown.</source>
          <target state="translated">예외가 throw 된 줄 번호를 나타내는 정수입니다.</target>       </trans-unit>
        <trans-unit id="130" translate="yes" xml:space="preserve">
          <source>Gets the column position in the object or XOML file that caused the exception to be thrown.</source>
          <target state="translated">개체 또는 예외를 throw XOML 파일의 열 위치를 가져옵니다.</target>       </trans-unit>
        <trans-unit id="131" translate="yes" xml:space="preserve">
          <source>An integer that represents the column position that caused the exception to be thrown.</source>
          <target state="translated">예외를 throw 한 열 위치를 나타내는 정수입니다.</target>       </trans-unit>
      </group>
    </body>
  </file>
</xliff>