<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">
  <file datatype="xml" original="markdown" source-language="en-US" target-language="ko-kr">
    <header>
      <tool tool-id="mdxliff" tool-name="mdxliff" tool-version="1.0-192e1fd" tool-company="Microsoft" />
      <xliffext:olfilehash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">8daefdfb260568b60a01c020330858051a308c3a</xliffext:olfilehash>
      <xliffext:olfilepath xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">fulldocset\System.IdentityModel.Selectors.StsCommunicationException.yml</xliffext:olfilepath>
      <xliffext:oltranslationpriority xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">fulldocset</xliffext:oltranslationpriority>
      <xliffext:oltranslationtype xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">Human Translation</xliffext:oltranslationtype>
      <xliffext:olskeletonhash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">b8826ee9cff5a8082f761a1fc38c926913c9b619</xliffext:olskeletonhash>
      <xliffext:olxliffhash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">4802a8a6a3bc995607be3abfee7a9b308c338bba</xliffext:olxliffhash>
    </header>
    <body>
      <group id="content" extype="content">
        <trans-unit id="101" translate="yes" xml:space="preserve">
          <source>The exception that is thrown when there is a problem communicating with the security token service.</source>
          <target state="translated">보안 토큰 서비스와 통신 하는 문제가 발생할 때 throw 되는 예외입니다.</target>       </trans-unit>
        <trans-unit id="102" translate="yes" xml:space="preserve" extradata="MT">
          <source>The problem can be caused by the following conditions: (1) Network failure (2) Failure to reach the MEX endpoint (3) Security token service does not have a valid endpoint identity</source>
          <target state="translated">이 문제는 다음과 같은 조건에서 발생할 수 있습니다. (1) 네트워크 오류 (2) 유효한 끝점 id (3) 보안 토큰 서비스에 없는 MEX 끝점 도달 실패</target>       </trans-unit>
        <trans-unit id="103" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.IdentityModel.Selectors.StsCommunicationException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class.</source>
          <target state="translated">새 인스턴스를 초기화는 <bpt id="p1">&lt;xref href="System.IdentityModel.Selectors.StsCommunicationException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> 클래스입니다.</target>       </trans-unit>
        <trans-unit id="104" translate="yes" xml:space="preserve">
          <source>Initializes an instance of the <bpt id="p1">&lt;xref href="System.IdentityModel.Selectors.StsCommunicationException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with the specified error message.</source>
          <target state="translated">인스턴스를 초기화는 <bpt id="p1">&lt;xref href="System.IdentityModel.Selectors.StsCommunicationException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> 지정된 된 오류 메시지를 사용 하 여 클래스입니다.</target>       </trans-unit>
        <trans-unit id="105" translate="yes" xml:space="preserve" extradata="MT">
          <source>This constructor initializes the &lt;xref:System.Exception.Message%2A&gt; property of the new instance to a system-supplied message that describes the error.</source>
          <target state="translated">이 생성자는 &lt;xref:System.Exception.Message%2A&gt;속성의 새 인스턴스를 오류를 설명 하는 시스템 제공 메시지로.&lt;/xref:System.Exception.Message%2A&gt;</target>       </trans-unit>
        <trans-unit id="106" translate="yes" xml:space="preserve" extradata="MT">
          <source>The content of the message should also be understandable to the user.</source>
          <target state="translated">메시지의 내용을 사용자에 게 이해할 수 해야 합니다.</target>       </trans-unit>
        <trans-unit id="107" translate="yes" xml:space="preserve">
          <source>The message that describes the error.</source>
          <target state="translated">오류를 설명 하는 메시지입니다.</target>       </trans-unit>
        <trans-unit id="108" translate="yes" xml:space="preserve">
          <source>Initializes an instance of the <bpt id="p1">&lt;xref href="System.IdentityModel.Selectors.StsCommunicationException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with serialized data.</source>
          <target state="translated">인스턴스를 초기화는 <bpt id="p1">&lt;xref href="System.IdentityModel.Selectors.StsCommunicationException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> serialize 된 데이터 클래스입니다.</target>       </trans-unit>
        <trans-unit id="109" translate="yes" xml:space="preserve" extradata="MT">
          <source>This constructor is called during deserialization to reconstitute the exception object transmitted over a stream.</source>
          <target state="translated">이 생성자는 스트림을 통해 전송 된 예외 개체를 다시 구성 하기 위해 역직렬화 하는 동안 호출 됩니다.</target>       </trans-unit>
        <trans-unit id="110" translate="yes" xml:space="preserve">
          <source>The <bpt id="p1">&lt;xref href="System.Runtime.Serialization.SerializationInfo"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> object that contains the serialized object data about the exception that is being thrown.</source>
          <target state="translated"><bpt id="p1">&lt;xref href="System.Runtime.Serialization.SerializationInfo"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> throw 되는 예외에 대 한 직렬화 된 개체 데이터를 포함 하는 개체입니다.</target>       </trans-unit>
        <trans-unit id="111" translate="yes" xml:space="preserve">
          <source>The &lt;xref:System.Runtime.Serialization.StreamingContext&gt; object that contains contextual information about the source or destination.</source>
          <target state="translated">&lt;xref:System.Runtime.Serialization.StreamingContext&gt;소스 또는 대상에 대 한 컨텍스트 정보를 포함 하는 개체입니다.&lt;/xref:System.Runtime.Serialization.StreamingContext&gt;</target>       </trans-unit>
        <trans-unit id="112" translate="yes" xml:space="preserve">
          <source>Initializes an instance of the <bpt id="p1">&lt;xref href="System.IdentityModel.Selectors.StsCommunicationException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with the specified error message and a reference to the inner exception that is the cause of this exception.</source>
          <target state="translated">인스턴스를 초기화는 <bpt id="p1">&lt;xref href="System.IdentityModel.Selectors.StsCommunicationException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> 지정된 된 오류 메시지와 해당 예외의 원인인 내부 예외에 대 한 참조를 사용 하 여 클래스입니다.</target>       </trans-unit>
        <trans-unit id="113" translate="yes" xml:space="preserve" extradata="MT">
          <source>An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the &lt;xref:System.Exception.InnerException%2A&gt; property.</source>
          <target state="translated">이전 예외의 직접적인 결과에 이전 예외에 대 한 참조가 들어 있어야 throw 되는 예외는 &lt;xref:System.Exception.InnerException%2A&gt;속성.&lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="114" translate="yes" xml:space="preserve" extradata="MT">
          <source>The &lt;xref:System.Exception.InnerException%2A&gt; property returns the same value that is passed into the constructor, or <ph id="ph1">`null`</ph> if the &lt;xref:System.Exception.InnerException%2A&gt; property does not supply the inner exception value to the constructor.</source>
          <target state="translated">&lt;xref:System.Exception.InnerException%2A&gt;속성은 생성자에 전달 되는 동일한 값을 반환 하거나 <ph id="ph1">`null`</ph> 경우는 &lt;xref:System.Exception.InnerException%2A&gt;생성자에 내부 예외 값을 제공 하지 않는.&lt;/xref:System.Exception.InnerException%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="115" translate="yes" xml:space="preserve">
          <source>The message that describes the error.</source>
          <target state="translated">오류를 설명 하는 메시지입니다.</target>       </trans-unit>
        <trans-unit id="116" translate="yes" xml:space="preserve">
          <source>The exception that is the cause of the current exception.</source>
          <target state="translated">현재 예외의 원인인 예외입니다.</target>       </trans-unit>
      </group>
    </body>
  </file>
</xliff>