<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">
  <file datatype="xml" original="markdown" source-language="en-US" target-language="zh-cn">
    <header>
      <tool tool-id="mdxliff" tool-name="mdxliff" tool-version="1.0-192e1fd" tool-company="Microsoft" />
      <xliffext:olfilehash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">4084675d596cccb30786101008d0be8940530b63</xliffext:olfilehash>
      <xliffext:olfilepath xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">fulldocset\System.Threading.ThreadStateException.yml</xliffext:olfilepath>
      <xliffext:oltranslationpriority xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">fulldocset</xliffext:oltranslationpriority>
      <xliffext:oltranslationtype xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">Human Translation</xliffext:oltranslationtype>
      <xliffext:olskeletonhash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">32ff1966449c5bf2a1c2ee687c5fb336beb152b6</xliffext:olskeletonhash>
      <xliffext:olxliffhash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">ae12339eb0798506e3a0e2be3f9ff4bbeece600f</xliffext:olxliffhash>
    </header>
    <body>
      <group id="content" extype="content">
        <trans-unit id="101" translate="yes" xml:space="preserve">
          <source>The exception that is thrown when a <bpt id="p1">&lt;xref href="System.Threading.Thread"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> is in an invalid &lt;xref:System.Threading.Thread.ThreadState*&gt; for the method call.</source>
          <target state="translated">时，将引发的异常<bpt id="p1">&lt;xref href="System.Threading.Thread"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept>无效&lt;xref:System.Threading.Thread.ThreadState*&gt;对于方法调用。&lt;/xref:System.Threading.Thread.ThreadState*&gt;</target>       </trans-unit>
        <trans-unit id="102" translate="yes" xml:space="preserve">
          <source>Once a thread is created, it is in at least one of the &lt;xref:System.Threading.ThreadState&gt; states until it terminates.</source>
          <target state="translated">线程创建后，它是中的至少一个&lt;xref:System.Threading.ThreadState&gt;状态中，直到它终止。&lt;/xref:System.Threading.ThreadState&gt;</target>       </trans-unit>
        <trans-unit id="103" translate="yes" xml:space="preserve">
          <source><ph id="ph1">`ThreadStateException`</ph> is thrown by methods that cannot perform the requested operation due to the current state of a thread.</source>
          <target state="translated"><ph id="ph1">`ThreadStateException`</ph>由无法执行请求的操作由于线程的当前状态的方法引发。</target>       </trans-unit>
        <trans-unit id="104" translate="yes" xml:space="preserve">
          <source>For example, trying to restart an aborted thread by calling &lt;xref:System.Threading.Thread.Start%2A&gt; on a thread that has terminated throws a ThreadStateException.</source>
          <target state="translated">例如，尝试重新启动已中止的线程调用&lt;xref:System.Threading.Thread.Start%2A&gt;已终止的线程上引发 ThreadStateException。&lt;/xref:System.Threading.Thread.Start%2A&gt;</target>       </trans-unit>
        <trans-unit id="105" translate="yes" xml:space="preserve">
          <source>ThreadStateException uses the HRESULT COR_E_THREADSTATE, which has the value 0x80131520.</source>
          <target state="translated">ThreadStateException 使用 HRESULT COR_E_THREADSTATE，其值 0x80131520。</target>       </trans-unit>
        <trans-unit id="106" translate="yes" xml:space="preserve">
          <source>For a list of initial property values for an instance of ThreadStateException, see the &lt;xref:System.Threading.ThreadStateException.%23ctor%2A&gt; constructors.</source>
          <target state="translated">ThreadStateException 的实例的初始属性值的列表，请参阅&lt;xref:System.Threading.ThreadStateException.%23ctor%2A&gt;构造函数。&lt;/xref:System.Threading.ThreadStateException.%23ctor%2A&gt;</target>       </trans-unit>
        <trans-unit id="107" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.Threading.ThreadStateException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with default properties.</source>
          <target state="translated">初始化的新实例<bpt id="p1">&lt;xref href="System.Threading.ThreadStateException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept>使用默认属性的类。</target>       </trans-unit>
        <trans-unit id="108" translate="yes" xml:space="preserve">
          <source>This constructor initializes the <ph id="ph1">`Message`</ph> property of the new instance to a system-supplied message that describes the error, such as "The requested operation cannot be performed on the thread due to its current state."</source>
          <target state="translated">此构造函数初始化<ph id="ph1">`Message`</ph>为系统提供的消息的描述错误，如"请求的操作无法执行由于其当前状态的线程上。"的新实例的属性</target>       </trans-unit>
        <trans-unit id="109" translate="yes" xml:space="preserve">
          <source>This message takes into account the current system culture.</source>
          <target state="translated">此消息将当前系统区域性考虑在内。</target>       </trans-unit>
        <trans-unit id="110" translate="yes" xml:space="preserve">
          <source>The following table shows the initial property values for an instance of &lt;xref:System.Threading.ThreadStateException&gt;.</source>
          <target state="translated">下表显示&lt;xref:System.Threading.ThreadStateException&gt;.&lt;/xref:System.Threading.ThreadStateException&gt;实例的初始属性的值</target>       </trans-unit>
        <trans-unit id="111" translate="yes" xml:space="preserve">
          <source>|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|<ph id="ph1">`null`</ph>.|   |&lt;xref:System.Exception.Message%2A&gt;|The localized error message string.|</source>
          <target state="translated">|属性 |值 |  |--------------|-----------|  |&lt;xref:System.Exception.InnerException%2A&gt;|<ph id="ph1">`null`</ph>.|  |&lt;xref:System.Exception.Message%2A&gt;|本地化的错误消息字符串。 |&lt;/xref:System.Exception.Message%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="112" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.Threading.ThreadStateException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with a specified error message.</source>
          <target state="translated">初始化的新实例<bpt id="p1">&lt;xref href="System.Threading.ThreadStateException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept>与指定的错误消息的类。</target>       </trans-unit>
        <trans-unit id="113" translate="yes" xml:space="preserve">
          <source>This constructor initializes the <ph id="ph1">`Message`</ph> property of the new instance using the <ph id="ph2">`message`</ph> parameter.</source>
          <target state="translated">此构造函数初始化<ph id="ph1">`Message`</ph>属性的新实例使用<ph id="ph2">`message`</ph>参数。</target>       </trans-unit>
        <trans-unit id="114" translate="yes" xml:space="preserve">
          <source>The following table shows the initial property values for an instance of &lt;xref:System.Threading.ThreadStateException&gt;.</source>
          <target state="translated">下表显示&lt;xref:System.Threading.ThreadStateException&gt;.&lt;/xref:System.Threading.ThreadStateException&gt;实例的初始属性的值</target>       </trans-unit>
        <trans-unit id="115" translate="yes" xml:space="preserve">
          <source>|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|<ph id="ph1">`null`</ph>.|   |&lt;xref:System.Exception.Message%2A&gt;|The error message string.|</source>
          <target state="translated">|属性 |值 |  |--------------|-----------|  |&lt;xref:System.Exception.InnerException%2A&gt;|<ph id="ph1">`null`</ph>.|  |&lt;xref:System.Exception.Message%2A&gt;|错误消息字符串。 |&lt;/xref:System.Exception.Message%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="116" translate="yes" xml:space="preserve">
          <source>The error message that explains the reason for the exception.</source>
          <target state="translated">解释异常原因的错误消息。</target>       </trans-unit>
        <trans-unit id="117" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.Threading.ThreadStateException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with serialized data.</source>
          <target state="translated">初始化的新实例<bpt id="p1">&lt;xref href="System.Threading.ThreadStateException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept>用序列化数据的类。</target>       </trans-unit>
        <trans-unit id="118" translate="yes" xml:space="preserve">
          <source>This constructor is called during deserialization to reconstitute the exception object transmitted over a stream.</source>
          <target state="translated">在反序列化，以便重建通过流传输的异常对象过程中调用此构造函数。</target>       </trans-unit>
        <trans-unit id="119" translate="yes" xml:space="preserve">
          <source>For more information, see <bpt id="p1">[</bpt>XML and SOAP Serialization<ept id="p1">](~/add/includes/ajax-current-ext-md.md)</ept>.</source>
          <target state="translated">有关详细信息，请参阅<bpt id="p1">[</bpt>XML 和 SOAP 序列化<ept id="p1">](~/add/includes/ajax-current-ext-md.md)</ept>。</target>       </trans-unit>
        <trans-unit id="120" translate="yes" xml:space="preserve">
          <source>The <bpt id="p1">&lt;xref href="System.Runtime.Serialization.SerializationInfo"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> that holds the serialized object data about the exception being thrown.</source>
          <target state="translated"><bpt id="p1">&lt;xref href="System.Runtime.Serialization.SerializationInfo"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept>它保存关于所引发异常的序列化的对象数据。</target>       </trans-unit>
        <trans-unit id="121" translate="yes" xml:space="preserve">
          <source>The &lt;xref:System.Runtime.Serialization.StreamingContext&gt; that contains contextual information about the source or destination.</source>
          <target state="translated">&lt;xref:System.Runtime.Serialization.StreamingContext&gt;它包含有关源或目标的上下文信息。&lt;/xref:System.Runtime.Serialization.StreamingContext&gt;</target>       </trans-unit>
        <trans-unit id="122" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.Threading.ThreadStateException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with a specified error message and a reference to the inner exception that is the cause of this exception.</source>
          <target state="translated">初始化的新实例<bpt id="p1">&lt;xref href="System.Threading.ThreadStateException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept>使用指定的错误消息和对导致此异常的内部异常的引用的类。</target>       </trans-unit>
        <trans-unit id="123" translate="yes" xml:space="preserve">
          <source>An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the &lt;xref:System.Exception.InnerException%2A&gt; property.</source>
          <target state="translated">前一个异常的直接结果应包含中的前一个异常的引用引发的异常，&lt;xref:System.Exception.InnerException%2A&gt;属性。&lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="124" translate="yes" xml:space="preserve">
          <source>The &lt;xref:System.Exception.InnerException%2A&gt; property returns the same value that is passed into the constructor, or <ph id="ph1">`null`</ph> if the &lt;xref:System.Exception.InnerException%2A&gt; property does not supply the inner exception value to the constructor.</source>
          <target state="translated">&lt;xref:System.Exception.InnerException%2A&gt;属性返回相同的值传递到构造函数中，或<ph id="ph1">`null`</ph>如果&lt;xref:System.Exception.InnerException%2A&gt;属性不会提供给构造函数的内部异常值。&lt;/xref:System.Exception.InnerException%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="125" translate="yes" xml:space="preserve">
          <source>The following table shows the initial property values for an instance of &lt;xref:System.Threading.ThreadStateException&gt;.</source>
          <target state="translated">下表显示&lt;xref:System.Threading.ThreadStateException&gt;.&lt;/xref:System.Threading.ThreadStateException&gt;实例的初始属性的值</target>       </trans-unit>
        <trans-unit id="126" translate="yes" xml:space="preserve">
          <source>|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|The inner exception reference.|   |&lt;xref:System.Exception.Message%2A&gt;|The error message string.|</source>
          <target state="translated">|属性 |值 |  |--------------|-----------|  |&lt;xref:System.Exception.InnerException%2A&gt;|内部异常引用。 |  |&lt;xref:System.Exception.Message%2A&gt;|错误消息字符串。 |&lt;/xref:System.Exception.Message%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="127" translate="yes" xml:space="preserve">
          <source>The error message that explains the reason for the exception.</source>
          <target state="translated">解释异常原因的错误消息。</target>       </trans-unit>
        <trans-unit id="128" translate="yes" xml:space="preserve">
          <source>The exception that is the cause of the current exception.</source>
          <target state="translated">导致当前异常的异常。</target>       </trans-unit>
        <trans-unit id="129" translate="yes" xml:space="preserve">
          <source>If the <ph id="ph1">`innerException`</ph> parameter is not <bpt id="p1">&lt;xref uid="langword_csharp_null" name="null" href=""&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept>, the current exception is raised in a <bpt id="p2">&lt;xref uid="langword_csharp_catch" name="catch" href=""&gt;</bpt><ept id="p2">&lt;/xref&gt;</ept> block that handles the inner exception.</source>
          <target state="translated">如果<ph id="ph1">`innerException`</ph>参数不是<bpt id="p1">&lt;xref uid="langword_csharp_null" name="null" href=""&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept>中, 引发当前异常<bpt id="p2">&lt;xref uid="langword_csharp_catch" name="catch" href=""&gt;</bpt><ept id="p2">&lt;/xref&gt;</ept>处理内部异常的块。</target>       </trans-unit>
      </group>
    </body>
  </file>
</xliff>