<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">
  <file datatype="xml" original="markdown" source-language="en-US" target-language="sv-se">
    <header>
      <tool tool-id="mdxliff" tool-name="mdxliff" tool-version="1.0-192e1fd" tool-company="Microsoft" />
      <xliffext:olfilehash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">22bf8524cc579fed8b5a402d9f71566126eb3695</xliffext:olfilehash>
      <xliffext:olfilepath xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">fulldocset\System.Security.Cryptography.CryptographicUnexpectedOperationException.yml</xliffext:olfilepath>
      <xliffext:oltranslationpriority xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">fulldocset</xliffext:oltranslationpriority>
      <xliffext:oltranslationtype xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">Human Translation</xliffext:oltranslationtype>
      <xliffext:olskeletonhash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">69398cf8d3672746b20af28c19a4906aafe79b54</xliffext:olskeletonhash>
      <xliffext:olxliffhash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">b6e9766b6fe3437d8040f5dcc7c7bed8e711132d</xliffext:olxliffhash>
    </header>
    <body>
      <group id="content" extype="content">
        <trans-unit id="101" translate="yes" xml:space="preserve">
          <source>The exception that is thrown when an unexpected operation occurs during a cryptographic operation.</source>
          <target state="translated">Undantag som utlöses när en oväntad åtgärd som uppstår under en krypteringsåtgärd.</target>       </trans-unit>
        <trans-unit id="102" translate="yes" xml:space="preserve" extradata="MT">
          <source>CryptographicUnexpectedOperationException uses the HRESULT CORSEC_E_CRYPTO_UNEX_OPER, which has the value 0x80131431.</source>
          <target state="translated">CryptographicUnexpectedOperationException använder HRESULT CORSEC_E_CRYPTO_UNEX_OPER, som har värdet 0x80131431.</target>       </trans-unit>
        <trans-unit id="103" translate="yes" xml:space="preserve" extradata="MT">
          <source>For a list of initial property values for an instance of CryptographicUnexpectedOperationException, see the constructor.</source>
          <target state="translated">En lista med inledande egenskapsvärden för en instans av CryptographicUnexpectedOperationException finns i konstruktorn.</target>       </trans-unit>
        <trans-unit id="104" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.Security.Cryptography.CryptographicUnexpectedOperationException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with default properties.</source>
          <target state="translated">Initierar en ny instans av den <bpt id="p1">&lt;xref href="System.Security.Cryptography.CryptographicUnexpectedOperationException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> klass med standardegenskaper.</target>       </trans-unit>
        <trans-unit id="105" translate="yes" xml:space="preserve" extradata="MT">
          <source>The following table shows the initial property values for an instance of &lt;xref:System.Security.Cryptography.CryptographicUnexpectedOperationException&gt;.</source>
          <target state="translated">I följande tabell visas de inledande egenskapsvärdena för en instans av &lt;xref:System.Security.Cryptography.CryptographicUnexpectedOperationException&gt;.&lt;/xref:System.Security.Cryptography.CryptographicUnexpectedOperationException&gt;</target>       </trans-unit>
        <trans-unit id="106" translate="yes" xml:space="preserve" extradata="MT">
          <source>|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|<ph id="ph1">`null`</ph>.|   |&lt;xref:System.Exception.Message%2A&gt;|The localized error message string.|</source>
          <target state="translated">| Egenskapen | Värdet |   |--------------|-----------|   | &lt;xref:System.Exception.InnerException%2A&gt;| <ph id="ph1">`null`</ph>.|   | &lt;xref:System.Exception.Message%2A&gt;| Den lokaliserade felsträngen meddelande. |&lt;/xref:System.Exception.Message%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="107" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.Security.Cryptography.CryptographicUnexpectedOperationException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with a specified error message.</source>
          <target state="translated">Initierar en ny instans av den <bpt id="p1">&lt;xref href="System.Security.Cryptography.CryptographicUnexpectedOperationException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> klass med ett angivet meddelande.</target>       </trans-unit>
        <trans-unit id="108" translate="yes" xml:space="preserve" extradata="MT">
          <source>The following table shows the initial property values for an instance of &lt;xref:System.Security.Cryptography.CryptographicUnexpectedOperationException&gt;.</source>
          <target state="translated">I följande tabell visas de inledande egenskapsvärdena för en instans av &lt;xref:System.Security.Cryptography.CryptographicUnexpectedOperationException&gt;.&lt;/xref:System.Security.Cryptography.CryptographicUnexpectedOperationException&gt;</target>       </trans-unit>
        <trans-unit id="109" translate="yes" xml:space="preserve" extradata="MT">
          <source>|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|<ph id="ph1">`null`</ph>.|   |&lt;xref:System.Exception.Message%2A&gt;|The error message string.|</source>
          <target state="translated">| Egenskapen | Värdet |   |--------------|-----------|   | &lt;xref:System.Exception.InnerException%2A&gt;| <ph id="ph1">`null`</ph>.|   | &lt;xref:System.Exception.Message%2A&gt;| Meddelandet felsträng. |&lt;/xref:System.Exception.Message%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="110" translate="yes" xml:space="preserve">
          <source>The error message that explains the reason for the exception.</source>
          <target state="translated">Felmeddelandet som förklarar orsaken till undantaget.</target>       </trans-unit>
        <trans-unit id="111" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.Security.Cryptography.CryptographicUnexpectedOperationException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with serialized data.</source>
          <target state="translated">Initierar en ny instans av den <bpt id="p1">&lt;xref href="System.Security.Cryptography.CryptographicUnexpectedOperationException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> klass med serialiserade data.</target>       </trans-unit>
        <trans-unit id="112" translate="yes" xml:space="preserve" extradata="MT">
          <source>This constructor is called during deserialization to reconstitute the exception object transmitted over a stream.</source>
          <target state="translated">Den här konstruktorn anropas under deserialisering till att fylla Undantagsobjektet som överförs via en dataström.</target>       </trans-unit>
        <trans-unit id="113" translate="yes" xml:space="preserve">
          <source>The object that holds the serialized object data.</source>
          <target state="translated">Det objekt som innehåller objektdata som serialiserade.</target>       </trans-unit>
        <trans-unit id="114" translate="yes" xml:space="preserve">
          <source>The contextual information about the source or destination.</source>
          <target state="translated">Detaljerad information om käll- och målservrar.</target>       </trans-unit>
        <trans-unit id="115" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.Security.Cryptography.CryptographicUnexpectedOperationException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with a specified error message and a reference to the inner exception that is the cause of this exception.</source>
          <target state="translated">Initierar en ny instans av den <bpt id="p1">&lt;xref href="System.Security.Cryptography.CryptographicUnexpectedOperationException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> klass med ett angivet meddelande och en referens till det interna undantaget som är orsaken till det här undantaget.</target>       </trans-unit>
        <trans-unit id="116" translate="yes" xml:space="preserve" extradata="MT">
          <source>An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the &lt;xref:System.Exception.InnerException%2A&gt; property.</source>
          <target state="translated">Ett undantag som utlöses när ett direkt resultat av ett tidigare undantag ska innehålla en referens till det tidigare undantaget i den &lt;xref:System.Exception.InnerException%2A&gt;egenskapen.&lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="117" translate="yes" xml:space="preserve" extradata="MT">
          <source>The &lt;xref:System.Exception.InnerException%2A&gt; property returns the same value that is passed into the constructor, or <ph id="ph1">`null`</ph> if the &lt;xref:System.Exception.InnerException%2A&gt; property does not supply the inner exception value to the constructor.</source>
          <target state="translated">Den &lt;xref:System.Exception.InnerException%2A&gt;-egenskap returnerar samma värde som överförs till konstruktorn eller <ph id="ph1">`null`</ph> om den &lt;xref:System.Exception.InnerException%2A&gt;egenskapen tillhandahåller inte värdet i det interna undantaget för konstruktorn.&lt;/xref:System.Exception.InnerException%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="118" translate="yes" xml:space="preserve" extradata="MT">
          <source>The following table shows the initial property values for an instance of &lt;xref:System.Security.Cryptography.CryptographicUnexpectedOperationException&gt;.</source>
          <target state="translated">I följande tabell visas de inledande egenskapsvärdena för en instans av &lt;xref:System.Security.Cryptography.CryptographicUnexpectedOperationException&gt;.&lt;/xref:System.Security.Cryptography.CryptographicUnexpectedOperationException&gt;</target>       </trans-unit>
        <trans-unit id="119" translate="yes" xml:space="preserve" extradata="MT">
          <source>|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|The inner exception reference.|   |&lt;xref:System.Exception.Message%2A&gt;|The error message string.|</source>
          <target state="translated">| Egenskapen | Värdet |   |--------------|-----------|   | &lt;xref:System.Exception.InnerException%2A&gt;| Referens för inre undantag. |   | &lt;xref:System.Exception.Message%2A&gt;| Meddelandet felsträng. |&lt;/xref:System.Exception.Message%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="120" translate="yes" xml:space="preserve">
          <source>The error message that explains the reason for the exception.</source>
          <target state="translated">Felmeddelandet som förklarar orsaken till undantaget.</target>       </trans-unit>
        <trans-unit id="121" translate="yes" xml:space="preserve">
          <source>The exception that is the cause of the current exception.</source>
          <target state="translated">Undantag som är orsaken till det aktuella undantaget.</target>       </trans-unit>
        <trans-unit id="122" translate="yes" xml:space="preserve">
          <source>If the <ph id="ph1">`inner`</ph> parameter is not <bpt id="p1">&lt;xref uid="langword_csharp_null" name="null" href=""&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept>, the current exception is raised in a <bpt id="p2">&lt;xref uid="langword_csharp_catch" name="catch" href=""&gt;</bpt><ept id="p2">&lt;/xref&gt;</ept> block that handles the inner exception.</source>
          <target state="translated">Om den <ph id="ph1">`inner`</ph> parametern är inte <bpt id="p1">&lt;xref uid="langword_csharp_null" name="null" href=""&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept>, det aktuella undantaget utlöses i en <bpt id="p2">&lt;xref uid="langword_csharp_catch" name="catch" href=""&gt;</bpt> <ept id="p2">&lt;/xref&gt;</ept> block som hanterar det interna undantaget.</target>       </trans-unit>
        <trans-unit id="123" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.Security.Cryptography.CryptographicUnexpectedOperationException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with a specified error message in the specified format.</source>
          <target state="translated">Initierar en ny instans av den <bpt id="p1">&lt;xref href="System.Security.Cryptography.CryptographicUnexpectedOperationException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> klass med ett angivet felmeddelande i det angivna formatet.</target>       </trans-unit>
        <trans-unit id="124" translate="yes" xml:space="preserve" extradata="MT">
          <source>The following table shows the initial property values for an instance of &lt;xref:System.Security.Cryptography.CryptographicUnexpectedOperationException&gt;.</source>
          <target state="translated">I följande tabell visas de inledande egenskapsvärdena för en instans av &lt;xref:System.Security.Cryptography.CryptographicUnexpectedOperationException&gt;.&lt;/xref:System.Security.Cryptography.CryptographicUnexpectedOperationException&gt;</target>       </trans-unit>
        <trans-unit id="125" translate="yes" xml:space="preserve" extradata="MT">
          <source>|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|<ph id="ph1">`null`</ph>.|   |&lt;xref:System.Exception.Message%2A&gt;|The error message string.|</source>
          <target state="translated">| Egenskapen | Värdet |   |--------------|-----------|   | &lt;xref:System.Exception.InnerException%2A&gt;| <ph id="ph1">`null`</ph>.|   | &lt;xref:System.Exception.Message%2A&gt;| Meddelandet felsträng. |&lt;/xref:System.Exception.Message%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="126" translate="yes" xml:space="preserve">
          <source>The format used to output the error message.</source>
          <target state="translated">Det format som används för att spara ett felmeddelande.</target>       </trans-unit>
        <trans-unit id="127" translate="yes" xml:space="preserve">
          <source>The error message that explains the reason for the exception.</source>
          <target state="translated">Felmeddelandet som förklarar orsaken till undantaget.</target>       </trans-unit>
      </group>
    </body>
  </file>
</xliff>