<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">
  <file datatype="xml" original="markdown" source-language="en-US" target-language="ja-jp">
    <header>
      <tool tool-id="mdxliff" tool-name="mdxliff" tool-version="1.0-192e1fd" tool-company="Microsoft" />
      <xliffext:olfilehash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">b6f0968e677edbe75c46dbf83183ad3d590b9abe</xliffext:olfilehash>
      <xliffext:olfilepath xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">fulldocset\System.Activities.Statements.TerminateWorkflow.yml</xliffext:olfilepath>
      <xliffext:oltranslationpriority xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">fulldocset</xliffext:oltranslationpriority>
      <xliffext:oltranslationtype xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">Human Translation</xliffext:oltranslationtype>
      <xliffext:olskeletonhash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">07aceb90c6677ca73dbc268173a49d4eaf1426de</xliffext:olskeletonhash>
      <xliffext:olxliffhash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">512a7aa84674108a0cd06d72a5b0c9bb5ce52462</xliffext:olxliffhash>
    </header>
    <body>
      <group id="content" extype="content">
        <trans-unit id="101" translate="yes" xml:space="preserve">
          <source>Terminates the running workflow instance, raises the &lt;xref:System.Activities.WorkflowApplication.Completed*&gt; event in the host, and reports error information.</source>
          <target state="translated">実行中のワークフロー インスタンスを終了、発生させる、&lt;xref:System.Activities.WorkflowApplication.Completed*&gt;ホスト、およびエラー情報をレポート内のイベント&lt;/xref:System.Activities.WorkflowApplication.Completed*&gt;。</target>       </trans-unit>
        <trans-unit id="102" translate="yes" xml:space="preserve">
          <source>Once the workflow is terminated, it cannot be resumed.</source>
          <target state="translated">ワークフローが終了した後は再開できません。</target>       </trans-unit>
        <trans-unit id="103" translate="yes" xml:space="preserve">
          <source>Creates a new instance of the <bpt id="p1">&lt;xref href="System.Activities.Statements.TerminateWorkflow"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class.</source>
          <target state="translated">新しいインスタンスを作成、 <bpt id="p1">&lt;xref href="System.Activities.Statements.TerminateWorkflow"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept>クラスです。</target>       </trans-unit>
        <trans-unit id="104" translate="yes" xml:space="preserve">
          <source>To be added.</source>
          <target state="translated">追加します。</target>       </trans-unit>
        <trans-unit id="105" translate="yes" xml:space="preserve">
          <source>Gets or sets the exception that provoked the instance termination.</source>
          <target state="translated">取得または設定をインスタンスの終了を引き起こした例外。</target>       </trans-unit>
        <trans-unit id="106" translate="yes" xml:space="preserve">
          <source>The exception that is passed to &lt;xref:System.Activities.WorkflowApplication.Terminate%2A&gt; is a &lt;xref:System.Activities.WorkflowApplicationTerminatedException&gt; if only &lt;xref:System.Activities.Statements.TerminateWorkflow.Reason%2A&gt; is set.</source>
          <target state="translated">渡される例外&lt;xref:System.Activities.WorkflowApplication.Terminate%2A&gt;は、&lt;xref:System.Activities.WorkflowApplicationTerminatedException&gt;のみ&lt;xref:System.Activities.Statements.TerminateWorkflow.Reason%2A&gt;設定されている&lt;/xref:System.Activities.Statements.TerminateWorkflow.Reason%2A&gt;&lt;/xref:System.Activities.WorkflowApplicationTerminatedException&gt;&lt;/xref:System.Activities.WorkflowApplication.Terminate%2A&gt;。</target>       </trans-unit>
        <trans-unit id="107" translate="yes" xml:space="preserve">
          <source>If only Exception is set, that exception is passed to &lt;xref:System.Activities.WorkflowApplication.Terminate%2A&gt;.</source>
          <target state="translated">その例外を&lt;xref:System.Activities.WorkflowApplication.Terminate%2A&gt;。&lt;/xref:System.Activities.WorkflowApplication.Terminate%2A&gt;に渡される場合のみ例外を設定すると、</target>       </trans-unit>
        <trans-unit id="108" translate="yes" xml:space="preserve">
          <source>If both &lt;xref:System.Activities.Statements.TerminateWorkflow.Reason%2A&gt; and Exception are set, a &lt;xref:System.Activities.WorkflowApplicationTerminatedException&gt; is passed with the specified &lt;xref:System.Activities.Statements.TerminateWorkflow.Reason%2A&gt;, and Exception is set as the exception’s &lt;xref:System.Exception.InnerException%2A&gt; property.</source>
          <target state="translated">両方&lt;xref:System.Activities.Statements.TerminateWorkflow.Reason%2A&gt;され、例外が設定、&lt;xref:System.Activities.WorkflowApplicationTerminatedException&gt;渡される、指定した&lt;xref:System.Activities.Statements.TerminateWorkflow.Reason%2A&gt;、例外は、例外の設定&lt;xref:System.Exception.InnerException%2A&gt;プロパティ&lt;/xref:System.Exception.InnerException%2A&gt;&lt;/xref:System.Activities.Statements.TerminateWorkflow.Reason%2A&gt;&lt;/xref:System.Activities.WorkflowApplicationTerminatedException&gt;&lt;/xref:System.Activities.Statements.TerminateWorkflow.Reason%2A&gt;。</target>       </trans-unit>
        <trans-unit id="109" translate="yes" xml:space="preserve">
          <source>If neither is set, a default &lt;xref:System.Activities.WorkflowApplicationTerminatedException&gt; is created.</source>
          <target state="translated">どちらも設定されている場合、既定の&lt;xref:System.Activities.WorkflowApplicationTerminatedException&gt;を作成します&lt;/xref:System.Activities.WorkflowApplicationTerminatedException&gt;。</target>       </trans-unit>
        <trans-unit id="110" translate="yes" xml:space="preserve">
          <source>The exception.</source>
          <target state="translated">例外。</target>       </trans-unit>
        <trans-unit id="111" translate="yes" xml:space="preserve">
          <source>To be added.</source>
          <target state="translated">追加します。</target>       </trans-unit>
        <trans-unit id="112" translate="yes" xml:space="preserve">
          <source>A string input argument with the reason for the workflow instance termination.</source>
          <target state="translated">文字列は、ワークフロー インスタンスを終了の理由を使用して引数を入力します。</target>       </trans-unit>
        <trans-unit id="113" translate="yes" xml:space="preserve">
          <source>The exception that is passed to &lt;xref:System.Activities.WorkflowApplication.Terminate%2A&gt; is a &lt;xref:System.Activities.WorkflowApplicationTerminatedException&gt; if only Reason is set.</source>
          <target state="translated">渡される例外&lt;xref:System.Activities.WorkflowApplication.Terminate%2A&gt;は、&lt;xref:System.Activities.WorkflowApplicationTerminatedException&gt;理由が設定されている場合のみです&lt;/xref:System.Activities.WorkflowApplicationTerminatedException&gt;&lt;/xref:System.Activities.WorkflowApplication.Terminate%2A&gt;。</target>       </trans-unit>
        <trans-unit id="114" translate="yes" xml:space="preserve">
          <source>If only &lt;xref:System.Activities.Statements.TerminateWorkflow.Exception%2A&gt; is set, that exception is passed to &lt;xref:System.Activities.WorkflowApplication.Terminate%2A&gt;.</source>
          <target state="translated">だけの場合&lt;xref:System.Activities.Statements.TerminateWorkflow.Exception%2A&gt;は設定すると、 &lt;xref:System.Activities.WorkflowApplication.Terminate%2A&gt;.&lt;/xref:System.Activities.WorkflowApplication.Terminate%2A&gt;に渡された例外&lt;/xref:System.Activities.Statements.TerminateWorkflow.Exception%2A&gt;</target>       </trans-unit>
        <trans-unit id="115" translate="yes" xml:space="preserve">
          <source>If both Reason and &lt;xref:System.Activities.Statements.TerminateWorkflow.Exception%2A&gt; are set, a &lt;xref:System.Activities.WorkflowApplicationTerminatedException&gt; is passed with the specified Reason, and &lt;xref:System.Activities.Statements.TerminateWorkflow.Exception%2A&gt; is set as the exception’s &lt;xref:System.Exception.InnerException%2A&gt; property.</source>
          <target state="translated">場合、両方の理由と&lt;xref:System.Activities.Statements.TerminateWorkflow.Exception%2A&gt;設定は、&lt;xref:System.Activities.WorkflowApplicationTerminatedException&gt;指定された理由と共に渡されると&lt;xref:System.Activities.Statements.TerminateWorkflow.Exception%2A&gt;、例外として設定されている&lt;xref:System.Exception.InnerException%2A&gt;プロパティ&lt;/xref:System.Exception.InnerException%2A&gt;&lt;/xref:System.Activities.Statements.TerminateWorkflow.Exception%2A&gt;&lt;/xref:System.Activities.WorkflowApplicationTerminatedException&gt;&lt;/xref:System.Activities.Statements.TerminateWorkflow.Exception%2A&gt;。</target>       </trans-unit>
        <trans-unit id="116" translate="yes" xml:space="preserve">
          <source>If neither is set, a default &lt;xref:System.Activities.WorkflowApplicationTerminatedException&gt; is created.</source>
          <target state="translated">どちらも設定されている場合、既定の&lt;xref:System.Activities.WorkflowApplicationTerminatedException&gt;を作成します&lt;/xref:System.Activities.WorkflowApplicationTerminatedException&gt;。</target>       </trans-unit>
        <trans-unit id="117" translate="yes" xml:space="preserve">
          <source>The reason for workflow termination.</source>
          <target state="translated">ワークフローの終了の理由です。</target>       </trans-unit>
      </group>
    </body>
  </file>
</xliff>