<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">
  <file datatype="xml" original="markdown" source-language="en-US" target-language="pt-pt">
    <header>
      <tool tool-id="mdxliff" tool-name="mdxliff" tool-version="1.0-192e1fd" tool-company="Microsoft" />
      <xliffext:olfilehash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">8af4e553a38643178cd2af1b789dc27a4c942c8b</xliffext:olfilehash>
      <xliffext:olfilepath xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">fulldocset\System.IO.DriveNotFoundException.yml</xliffext:olfilepath>
      <xliffext:oltranslationpriority xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">fulldocset</xliffext:oltranslationpriority>
      <xliffext:oltranslationtype xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">Human Translation</xliffext:oltranslationtype>
      <xliffext:olskeletonhash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">fcd5615ed373a8ae16c587b2ee19f176a5fe8eed</xliffext:olskeletonhash>
      <xliffext:olxliffhash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">7fbbdae807f7b9a1ff53b29b35e5539a24f9cb5e</xliffext:olxliffhash>
    </header>
    <body>
      <group id="content" extype="content">
        <trans-unit id="101" translate="yes" xml:space="preserve">
          <source>The exception that is thrown when trying to access a drive or share that is not available.</source>
          <target state="translated">A exceção que é acionada ao tentar aceder a uma unidade ou partilha que não está disponível.</target>       </trans-unit>
        <trans-unit id="102" translate="yes" xml:space="preserve" extradata="MT">
          <source>The DriveNotFoundException class uses the HRESULT COR_E_DIRECTORYNOTFOUND.</source>
          <target state="translated">A classe de DriveNotFoundException utiliza o COR_E_DIRECTORYNOTFOUND HRESULT.</target>       </trans-unit>
        <trans-unit id="103" translate="yes" xml:space="preserve" extradata="MT">
          <source>This exception can be thrown when a Win32 ERROR_PATH_NOT_FOUND HRESULT error is encountered.</source>
          <target state="translated">Esta exceção pode ser acionada quando é encontrado um erro do Win32 ERROR_PATH_NOT_FOUND HRESULT.</target>       </trans-unit>
        <trans-unit id="104" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.IO.DriveNotFoundException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with its message string set to a system-supplied message and its HRESULT set to COR_E_DIRECTORYNOTFOUND.</source>
          <target state="translated">Inicializa uma nova instância do <bpt id="p1">&lt;xref href="System.IO.DriveNotFoundException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> classe com a cadeia de mensagem definido como uma mensagem fornecido pelo sistema e o respetivo HRESULT definido como COR_E_DIRECTORYNOTFOUND.</target>       </trans-unit>
        <trans-unit id="105" translate="yes" xml:space="preserve" extradata="MT">
          <source>This constructor initializes the &lt;xref:System.Exception.Message%2A?displayProperty=fullName&gt; property of the new instance to a system-supplied message that describes the error, such as "Could not find the specified directory."</source>
          <target state="translated">Este construtor inicializa a &lt;xref:System.Exception.Message%2A?displayProperty=fullName&gt;propriedade da instância do novo a uma mensagem fornecido pelo sistema que descreve o erro, como "Não foi possível localizar o diretório especificado."&lt;/xref:System.Exception.Message%2A?displayProperty=fullName&gt;</target>       </trans-unit>
        <trans-unit id="106" translate="yes" xml:space="preserve" extradata="MT">
          <source>This message is localized based on the current system culture.</source>
          <target state="translated">Esta mensagem é localizada com base no idioma de sistema atual.</target>       </trans-unit>
        <trans-unit id="107" translate="yes" xml:space="preserve" extradata="MT">
          <source>The &lt;xref:System.Exception.InnerException%2A?displayProperty=fullName&gt; property of the new instance is initialized to <ph id="ph1">`null`</ph>.</source>
          <target state="translated">O &lt;xref:System.Exception.InnerException%2A?displayProperty=fullName&gt;propriedade da instância nova é inicializada para <ph id="ph1">`null`</ph>.&lt;/xref:System.Exception.InnerException%2A?displayProperty=fullName&gt;</target>       </trans-unit>
        <trans-unit id="108" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.IO.DriveNotFoundException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with the specified message string and the HRESULT set to COR_E_DIRECTORYNOTFOUND.</source>
          <target state="translated">Inicializa uma nova instância do <bpt id="p1">&lt;xref href="System.IO.DriveNotFoundException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> classe com a cadeia de mensagem especificado e o HRESULT definido como COR_E_DIRECTORYNOTFOUND.</target>       </trans-unit>
        <trans-unit id="109" translate="yes" xml:space="preserve" extradata="MT">
          <source>This constructor initializes the &lt;xref:System.Exception.Message%2A?displayProperty=fullName&gt; property of the new instance using the <ph id="ph1">`message`</ph> parameter.</source>
          <target state="translated">Este construtor inicializa a &lt;xref:System.Exception.Message%2A?displayProperty=fullName&gt;propriedade da nova instância utilizando o <ph id="ph1">`message`</ph> parâmetro.&lt;/xref:System.Exception.Message%2A?displayProperty=fullName&gt;</target>       </trans-unit>
        <trans-unit id="110" translate="yes" xml:space="preserve" extradata="MT">
          <source>The &lt;xref:System.Exception.InnerException%2A?displayProperty=fullName&gt; property of the new instance is initialized to <ph id="ph1">`null`</ph>.</source>
          <target state="translated">O &lt;xref:System.Exception.InnerException%2A?displayProperty=fullName&gt;propriedade da instância nova é inicializada para <ph id="ph1">`null`</ph>.&lt;/xref:System.Exception.InnerException%2A?displayProperty=fullName&gt;</target>       </trans-unit>
        <trans-unit id="111" translate="yes" xml:space="preserve">
          <source>A &lt;xref:System.String&gt; object that describes the error.</source>
          <target state="translated">A &lt;xref:System.String&gt;objeto que descreve o erro.&lt;/xref:System.String&gt;</target>       </trans-unit>
        <trans-unit id="112" translate="yes" xml:space="preserve">
          <source>The caller of this constructor is required to ensure that this string has been localized for the current system culture.</source>
          <target state="translated">O autor da chamada deste construtor não é necessária para se certificar de que esta cadeia tem foram localizada da cultura atual do sistema.</target>       </trans-unit>
        <trans-unit id="113" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.IO.DriveNotFoundException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with the specified serialization and context information.</source>
          <target state="translated">Inicializa uma nova instância do <bpt id="p1">&lt;xref href="System.IO.DriveNotFoundException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> classe com as informações de serialização e contexto especificadas.</target>       </trans-unit>
        <trans-unit id="114" translate="yes" xml:space="preserve">
          <source>A <bpt id="p1">&lt;xref href="System.Runtime.Serialization.SerializationInfo"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> object that contains the serialized object data about the exception being thrown.</source>
          <target state="translated">A <bpt id="p1">&lt;xref href="System.Runtime.Serialization.SerializationInfo"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> objeto que contém os dados de objecto serializado sobre a exceção que está a ser emitida.</target>       </trans-unit>
        <trans-unit id="115" translate="yes" xml:space="preserve">
          <source>A &lt;xref:System.Runtime.Serialization.StreamingContext&gt; object that contains contextual information about the source or destination of the exception being thrown.</source>
          <target state="translated">A &lt;xref:System.Runtime.Serialization.StreamingContext&gt;objeto que contém a nível contextual das informações sobre a origem ou de destino da exceção que está a ser emitida.&lt;/xref:System.Runtime.Serialization.StreamingContext&gt;</target>       </trans-unit>
        <trans-unit id="116" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.IO.DriveNotFoundException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with the specified error message and a reference to the inner exception that is the cause of this exception.</source>
          <target state="translated">Inicializa uma nova instância do <bpt id="p1">&lt;xref href="System.IO.DriveNotFoundException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> classe com a mensagem de erro especificado e uma referência a exceção interna que é a causa desta exceção.</target>       </trans-unit>
        <trans-unit id="117" translate="yes" xml:space="preserve" extradata="MT">
          <source>An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the &lt;xref:System.Exception.InnerException%2A&gt; property.</source>
          <target state="translated">Uma exceção que é acionada como um resultado direto de uma exceção anterior deve incluir uma referência a exceção anterior no &lt;xref:System.Exception.InnerException%2A&gt;propriedade.&lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="118" translate="yes" xml:space="preserve" extradata="MT">
          <source>The &lt;xref:System.Exception.InnerException%2A&gt; property returns the same value that is passed into the constructor, or <ph id="ph1">`null`</ph> if the &lt;xref:System.Exception.InnerException%2A&gt; property does not supply the inner exception value to the constructor.</source>
          <target state="translated">O &lt;xref:System.Exception.InnerException%2A&gt;propriedade devolve o mesmo valor que é transmitido para o construtor ou <ph id="ph1">`null`</ph> se o &lt;xref:System.Exception.InnerException%2A&gt;propriedade não fornecer o valor da exceção interna para o construtor.&lt;/xref:System.Exception.InnerException%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="119" translate="yes" xml:space="preserve" extradata="MT">
          <source>The following table shows the initial property values for an instance of &lt;xref:System.IO.DirectoryNotFoundException&gt;.</source>
          <target state="translated">A tabela seguinte mostra os valores de propriedade inicial para uma instância do &lt;xref:System.IO.DirectoryNotFoundException&gt;.&lt;/xref:System.IO.DirectoryNotFoundException&gt;</target>       </trans-unit>
        <trans-unit id="120" translate="yes" xml:space="preserve" extradata="MT">
          <source>|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|The inner exception reference.|   |&lt;xref:System.Exception.Message%2A&gt;|The error message string.|</source>
          <target state="translated">| Propriedade | Valor |   |--------------|-----------|   | &lt;xref:System.Exception.InnerException%2A&gt;| A referência a exceção interna. |   | &lt;xref:System.Exception.Message%2A&gt;| A cadeia de mensagem de erro. |&lt;/xref:System.Exception.Message%2A&gt; &lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="121" translate="yes" xml:space="preserve">
          <source>The error message that explains the reason for the exception.</source>
          <target state="translated">A mensagem de erro que explique a razão para a exceção.</target>       </trans-unit>
        <trans-unit id="122" translate="yes" xml:space="preserve">
          <source>The exception that is the cause of the current exception.</source>
          <target state="translated">A exceção é a causa da exceção atual.</target>       </trans-unit>
        <trans-unit id="123" translate="yes" xml:space="preserve">
          <source>If the <ph id="ph1">`innerException`</ph> parameter is not <bpt id="p1">&lt;xref uid="langword_csharp_null" name="null" href=""&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept>, the current exception is raised in a <bpt id="p2">&lt;xref uid="langword_csharp_catch" name="catch" href=""&gt;</bpt><ept id="p2">&lt;/xref&gt;</ept> block that handles the inner exception.</source>
          <target state="translated">Se o <ph id="ph1">`innerException`</ph> não é o parâmetro <bpt id="p1">&lt;xref uid="langword_csharp_null" name="null" href=""&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept>, a exceção atual num <bpt id="p2">&lt;xref uid="langword_csharp_catch" name="catch" href=""&gt;</bpt> <ept id="p2">&lt;/xref&gt;</ept> bloco que processa a exceção interna.</target>       </trans-unit>
      </group>
    </body>
  </file>
</xliff>