<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">
  <file datatype="xml" original="markdown" source-language="en-US" target-language="nb-no">
    <header>
      <tool tool-id="mdxliff" tool-name="mdxliff" tool-version="1.0-192e1fd" tool-company="Microsoft" />
      <xliffext:olfilehash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">05177edc37411cc0f0dc7984f7dd2e72975e8654</xliffext:olfilehash>
      <xliffext:olfilepath xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">fulldocset\System.Security.Authentication.InvalidCredentialException.yml</xliffext:olfilepath>
      <xliffext:oltranslationpriority xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">fulldocset</xliffext:oltranslationpriority>
      <xliffext:oltranslationtype xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">Human Translation</xliffext:oltranslationtype>
      <xliffext:olskeletonhash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">595cda76ef9e4c621b0c4571e647678417c5b588</xliffext:olskeletonhash>
      <xliffext:olxliffhash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">99b7e5ca2e629037217c03a8d16f747dffeb9d20</xliffext:olxliffhash>
    </header>
    <body>
      <group id="content" extype="content">
        <trans-unit id="101" translate="yes" xml:space="preserve">
          <source>The exception that is thrown when authentication fails for an authentication stream and cannot be retried.</source>
          <target state="translated">Unntaket oppstod under godkjenning mislykkes for godkjenning flyten og kan ikke kjøres.</target>       </trans-unit>
        <trans-unit id="102" translate="yes" xml:space="preserve" extradata="MT">
          <source>The &lt;xref:System.Net.Security.NegotiateStream&gt; and &lt;xref:System.Net.Security.SslStream&gt; classes throw this exception when authentication fails.</source>
          <target state="translated">Den &lt;xref:System.Net.Security.NegotiateStream&gt;og &lt;xref:System.Net.Security.SslStream&gt;klasser throw dette unntaket når godkjenning mislykkes.&lt;/xref:System.Net.Security.SslStream&gt; &lt;/xref:System.Net.Security.NegotiateStream&gt;</target>       </trans-unit>
        <trans-unit id="103" translate="yes" xml:space="preserve" extradata="MT">
          <source>This exception indicates that the underlying stream is not in a valid state and you cannot retry the authentication using the &lt;xref:System.Net.Security.NegotiateStream&gt; or &lt;xref:System.Net.Security.SslStream&gt; instance.</source>
          <target state="translated">Dette unntaket indikerer at den underliggende er ikke i en gyldig tilstand, og du kan prøve på nytt godkjenning ved hjelp av den &lt;xref:System.Net.Security.NegotiateStream&gt;eller &lt;xref:System.Net.Security.SslStream&gt;forekomsten.&lt;/xref:System.Net.Security.SslStream&gt; &lt;/xref:System.Net.Security.NegotiateStream&gt;</target>       </trans-unit>
        <trans-unit id="104" translate="yes" xml:space="preserve" extradata="MT">
          <source>If you can retry the authentication, an &lt;xref:System.Security.Authentication.AuthenticationException&gt; is thrown instead of the InvalidCredentialException.</source>
          <target state="translated">Hvis du kan prøve på nytt godkjenning, en &lt;xref:System.Security.Authentication.AuthenticationException&gt;er et i stedet for InvalidCredentialException.&lt;/xref:System.Security.Authentication.AuthenticationException&gt;</target>       </trans-unit>
        <trans-unit id="105" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.Security.Authentication.InvalidCredentialException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with no message.</source>
          <target state="translated">Initialiserer en ny forekomst av den <bpt id="p1">&lt;xref href="System.Security.Authentication.InvalidCredentialException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> klasse ingen melding.</target>       </trans-unit>
        <trans-unit id="106" translate="yes" xml:space="preserve" extradata="MT">
          <source>This constructor does nothing.</source>
          <target state="translated">Denne konstruktøren gjøre noe.</target>       </trans-unit>
        <trans-unit id="107" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.Security.Authentication.InvalidCredentialException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with the specified message.</source>
          <target state="translated">Initialiserer en ny forekomst av den <bpt id="p1">&lt;xref href="System.Security.Authentication.InvalidCredentialException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> klassen med den angitte meldingen.</target>       </trans-unit>
        <trans-unit id="108" translate="yes" xml:space="preserve" extradata="MT">
          <source>This constructor initializes the &lt;xref:System.Exception.Message%2A&gt; property with the text in the <ph id="ph1">`message`</ph> parameter.</source>
          <target state="translated">Denne konstruktøren initialiserer den &lt;xref:System.Exception.Message%2A&gt;egenskapen med teksten i den <ph id="ph1">`message`</ph> parameteren.&lt;/xref:System.Exception.Message%2A&gt;</target>       </trans-unit>
        <trans-unit id="109" translate="yes" xml:space="preserve" extradata="MT">
          <source>The &lt;xref:System.Exception.InnerException%2A&gt; property is set to <ph id="ph1">`null`</ph>.</source>
          <target state="translated">Den &lt;xref:System.Exception.InnerException%2A&gt;er satt til <ph id="ph1">`null`</ph>.&lt;/xref:System.Exception.InnerException%2A&gt;</target>       </trans-unit>
        <trans-unit id="110" translate="yes" xml:space="preserve">
          <source>A &lt;xref:System.String&gt; that describes the authentication failure.</source>
          <target state="translated">En &lt;xref:System.String&gt;som beskriver godkjenningsfeil.&lt;/xref:System.String&gt;</target>       </trans-unit>
        <trans-unit id="111" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.Security.Authentication.InvalidCredentialException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class from the specified instances of the <bpt id="p2">&lt;xref href="System.Runtime.Serialization.SerializationInfo"&gt;</bpt><ept id="p2">&lt;/xref&gt;</ept> and &lt;xref:System.Runtime.Serialization.StreamingContext&gt; classes.</source>
          <target state="translated">Initialiserer en ny forekomst av den <bpt id="p1">&lt;xref href="System.Security.Authentication.InvalidCredentialException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> klassen fra den angitte forekomsten av den <bpt id="p2">&lt;xref href="System.Runtime.Serialization.SerializationInfo"&gt;</bpt> <ept id="p2">&lt;/xref&gt;</ept> og &lt;xref:System.Runtime.Serialization.StreamingContext&gt;klasser.&lt;/xref:System.Runtime.Serialization.StreamingContext&gt;</target>       </trans-unit>
        <trans-unit id="112" translate="yes" xml:space="preserve">
          <source>A <bpt id="p1">&lt;xref href="System.Runtime.Serialization.SerializationInfo"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> instance that contains the information required to deserialize the new <bpt id="p2">&lt;xref href="System.Security.Authentication.InvalidCredentialException"&gt;</bpt><ept id="p2">&lt;/xref&gt;</ept> instance.</source>
          <target state="translated">En <bpt id="p1">&lt;xref href="System.Runtime.Serialization.SerializationInfo"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> forekomsten som inneholder informasjonen som kreves for deserialisering av det nye <bpt id="p2">&lt;xref href="System.Security.Authentication.InvalidCredentialException"&gt;</bpt> <ept id="p2">&lt;/xref&gt;</ept> forekomsten.</target>       </trans-unit>
        <trans-unit id="113" translate="yes" xml:space="preserve">
          <source>A &lt;xref:System.Runtime.Serialization.StreamingContext&gt; instance.</source>
          <target state="translated">En &lt;xref:System.Runtime.Serialization.StreamingContext&gt;forekomsten.&lt;/xref:System.Runtime.Serialization.StreamingContext&gt;</target>       </trans-unit>
        <trans-unit id="114" translate="yes" xml:space="preserve">
          <source>Initializes a new instance of the <bpt id="p1">&lt;xref href="System.Security.Authentication.InvalidCredentialException"&gt;</bpt><ept id="p1">&lt;/xref&gt;</ept> class with the specified message and inner exception.</source>
          <target state="translated">Initialiserer en ny forekomst av den <bpt id="p1">&lt;xref href="System.Security.Authentication.InvalidCredentialException"&gt;</bpt> <ept id="p1">&lt;/xref&gt;</ept> klassen med den angitte meldings- og indre unntaket.</target>       </trans-unit>
        <trans-unit id="115" translate="yes" xml:space="preserve" extradata="MT">
          <source>This constructor initializes the &lt;xref:System.Exception.Message%2A&gt; property with the text in the <ph id="ph1">`message`</ph> parameter and initializes the &lt;xref:System.Exception.InnerException%2A&gt; property with the <ph id="ph2">`innerException`</ph> parameter value.</source>
          <target state="translated">Denne konstruktøren initialiserer den &lt;xref:System.Exception.Message%2A&gt;egenskap med teksten i den <ph id="ph1">`message`</ph> parameteren og initialisere den &lt;xref:System.Exception.InnerException%2A&gt;egenskapen med den <ph id="ph2">`innerException`</ph> parameterverdi.&lt;/xref:System.Exception.InnerException%2A&gt; &lt;/xref:System.Exception.Message%2A&gt;</target>       </trans-unit>
        <trans-unit id="116" translate="yes" xml:space="preserve">
          <source>A &lt;xref:System.String&gt; that describes the authentication failure.</source>
          <target state="translated">En &lt;xref:System.String&gt;som beskriver godkjenningsfeil.&lt;/xref:System.String&gt;</target>       </trans-unit>
        <trans-unit id="117" translate="yes" xml:space="preserve">
          <source>The &lt;xref:System.Exception&gt; that is the cause of the current exception.</source>
          <target state="translated">Den &lt;xref:System.Exception&gt;som er årsaken til den gjeldende unntaket.&lt;/xref:System.Exception&gt;</target>       </trans-unit>
      </group>
    </body>
  </file>
</xliff>